; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ pymcu_random__state, _stack_base + 0
.equ tmp_105, _stack_base + 6
.equ tmp_107, _stack_base + 12
.equ tmp_109, _stack_base + 16
.equ tmp_110, _stack_base + 20
.equ tmp_112, _stack_base + 24
.equ tmp_114, _stack_base + 28
.equ tmp_108, _stack_base + 32
.equ main_on_ms, _stack_base + 34
.equ tmp_117, _stack_base + 36
.equ tmp_116, _stack_base + 40
.equ _s158fd138, _stack_base + 44
.equ _s610f894f, _stack_base + 44
.equ _s500f6e8c, _stack_base + 47
.equ pymcu_random_random_n, _stack_base + 44
.equ tmp_6, _stack_base + 46
.equ tmp_8, _stack_base + 50
.equ tmp_9, _stack_base + 54
.equ delay_ms_avr_ms, _stack_base + 44
.equ _bss_end, _stack_base + 4

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt


; --- PyMCU AVR Math Runtime ---
; -----------------------------------------------------------------------------
; PyMCU AVR Math Runtime
; -----------------------------------------------------------------------------
;
; __div32: Unsigned 32-bit Division
;   Input:  R23:R22:R25:R24 (Dividend, MSB..LSB), R21:R20:R19:R18 (Divisor)
;   Output: R23:R22:R25:R24 (Quotient)
;   Clobbers: R4-R7 (remainder), R16 (loop counter)
;   Note: R4-R7 and R16 are saved/restored via PUSH/POP.
;
; __mod32: Unsigned 32-bit Modulo
;   Input:  R23:R22:R25:R24 (Dividend), R21:R20:R19:R18 (Divisor)
;   Output: R23:R22:R25:R24 (Remainder)
;   Clobbers: R4-R7 (intermediate quotient), R16 (loop counter)
;
; Register layout (byte positions, LSB first):
;   byte0 = R24 (dividend / quotient LSB)
;   byte1 = R25
;   byte2 = R22
;   byte3 = R23 (dividend / quotient MSB)
;   divisor LSB = R18, byte1 = R19, byte2 = R20, MSB = R21
;   remainder LSB = R4, byte1 = R5, byte2 = R6, MSB = R7 (local, saved)
;
; Algorithm: Non-restoring bit-by-bit long division (33 iterations).
; -----------------------------------------------------------------------------

; __div32_core: shared inner loop used by both __div32 and __mod32.
;   Pre-condition: R4:R5:R6:R7 = 0 (remainder), R16 = 33 (counter).
;   Post-condition: R23:R22:R25:R24 = Quotient, R7:R6:R5:R4 = Remainder.
;   Does NOT save/restore any registers.
__div32_core:
__div32_core_loop:
    rol r24             ; Shift dividend left (LSB first carries out MSB)
    rol r25
    rol r22
    rol r23
    dec r16
    breq __div32_core_done
    rol r4              ; Shift remainder left, incoming dividend MSB in Carry
    rol r5
    rol r6
    rol r7
    sub r4, r18         ; Remainder -= Divisor
    sbc r5, r19
    sbc r6, r20
    sbc r7, r21
    brcc __div32_core_next  ; No borrow => remainder >= divisor
    add r4, r18         ; Restore remainder
    adc r5, r19
    adc r6, r20
    adc r7, r21
    clc                 ; Quotient bit = 0
    rjmp __div32_core_loop
__div32_core_next:
    sec                 ; Quotient bit = 1
    rjmp __div32_core_loop
__div32_core_done:
    ret

__div32:
    push r4
    push r5
    push r6
    push r7
    push r16
    clr r4
    clr r5
    clr r6
    clr r7
    ldi r16, 33
    rcall __div32_core
    pop r16
    pop r7
    pop r6
    pop r5
    pop r4
    ret

__mod32:
    push r4
    push r5
    push r6
    push r7
    push r16
    clr r4
    clr r5
    clr r6
    clr r7
    ldi r16, 33
    rcall __div32_core
    mov r24, r4         ; Move remainder to result registers
    mov r25, r5
    mov r22, r6
    mov r23, r7
    pop r16
    pop r7
    pop r6
    pop r5
    pop r4
    ret

; -----------------------------------------------------------------------------
; __divs32 / __mods32: SIGNED 32-bit floor division and modulo (Python).
;   Input:  R23:R22:R25:R24 (Dividend a, MSB..LSB), R21:R20:R19:R18 (Divisor b)
;   Output: __divs32 -> R23:R22:R25:R24 = floor(a/b)
;           __mods32 -> R23:R22:R25:R24 = a - b*floor(a/b)   (sign of b)
; Each is self-contained (one __div32_core pass). R4-R13 are saved/restored, so
; the net clobber matches __div32/__mod32 (R4-R7 used internally and restored);
; R16 (counter) and R0 (scratch) are caller-saved. 32-bit in-place negate:
;   com b3 / com b2 / com b1 / neg b0 / sbci b1 / sbci b2 / sbci b3 (each ,0xFF).
; -----------------------------------------------------------------------------
__divs32:
    push r4
    push r5
    push r6
    push r7
    push r8             ; sign(a)
    push r9             ; sign(b)
    mov  r8, r23
    mov  r9, r21
    sbrs r23, 7
    rjmp __divs32_absb
    com  r23            ; |a|
    com  r22
    com  r25
    neg  r24
    sbci r25, 0xFF
    sbci r22, 0xFF
    sbci r23, 0xFF
__divs32_absb:
    sbrs r21, 7
    rjmp __divs32_div
    com  r21            ; |b|
    com  r20
    com  r19
    neg  r18
    sbci r19, 0xFF
    sbci r20, 0xFF
    sbci r21, 0xFF
__divs32_div:
    clr  r4
    clr  r5
    clr  r6
    clr  r7
    ldi  r16, 33
    rcall __div32_core  ; quotient R23:R22:R25:R24 ; remainder R7:R6:R5:R4
    mov  r0, r8
    eor  r0, r9
    sbrs r0, 7
    rjmp __divs32_done  ; signs equal -> trunc quotient == floor
    com  r23            ; negate quotient
    com  r22
    com  r25
    neg  r24
    sbci r25, 0xFF
    sbci r22, 0xFF
    sbci r23, 0xFF
    mov  r0, r4         ; remainder != 0 ?
    or   r0, r5
    or   r0, r6
    or   r0, r7
    breq __divs32_done
    subi r24, 1         ; floor: q -= 1
    sbci r25, 0
    sbci r22, 0
    sbci r23, 0
__divs32_done:
    pop  r9
    pop  r8
    pop  r7
    pop  r6
    pop  r5
    pop  r4
    ret

__mods32:
    push r4
    push r5
    push r6
    push r7
    push r8             ; sign(a)
    push r9             ; sign(b)
    push r10            ; original b (signed): r13:r12:r11:r10
    push r11
    push r12
    push r13
    mov  r8, r23
    mov  r9, r21
    mov  r10, r18
    mov  r11, r19
    mov  r12, r20
    mov  r13, r21
    sbrs r23, 7
    rjmp __mods32_absb
    com  r23            ; |a|
    com  r22
    com  r25
    neg  r24
    sbci r25, 0xFF
    sbci r22, 0xFF
    sbci r23, 0xFF
__mods32_absb:
    sbrs r21, 7
    rjmp __mods32_div
    com  r21            ; |b|
    com  r20
    com  r19
    neg  r18
    sbci r19, 0xFF
    sbci r20, 0xFF
    sbci r21, 0xFF
__mods32_div:
    clr  r4
    clr  r5
    clr  r6
    clr  r7
    ldi  r16, 33
    rcall __div32_core  ; remainder R7:R6:R5:R4
    sbrs r8, 7
    rjmp __mods32_floor
    com  r4             ; truncating remainder takes the sign of a.
    com  r5             ; R4-R7 are low regs (no SBCI), so negate as ~v + 1 using the
    com  r6             ; zero register R1: complement all bytes, then add 1 with carry.
    com  r7
    sec
    adc  r4, r1
    adc  r5, r1
    adc  r6, r1
    adc  r7, r1
__mods32_floor:
    mov  r0, r8
    eor  r0, r9
    sbrs r0, 7
    rjmp __mods32_out   ; signs equal -> trunc remainder == floor
    mov  r0, r4         ; remainder != 0 ?
    or   r0, r5
    or   r0, r6
    or   r0, r7
    breq __mods32_out
    add  r4, r10        ; floor: r += original b
    adc  r5, r11
    adc  r6, r12
    adc  r7, r13
__mods32_out:
    mov  r24, r4        ; remainder -> output registers
    mov  r25, r5
    mov  r22, r6
    mov  r23, r7
    pop  r13
    pop  r12
    pop  r11
    pop  r10
    pop  r9
    pop  r8
    pop  r7
    pop  r6
    pop  r5
    pop  r4
    ret

; -----------------------------------------------------------------------------
; PyMCU AVR Math Runtime
; -----------------------------------------------------------------------------
;
; __mul32: Unsigned 32-bit Multiplication (low 32 bits of the product)
;   Input:  R23:R22:R25:R24 (a, MSB..LSB), R21:R20:R19:R18 (b, MSB..LSB)
;   Output: R23:R22:R25:R24 (low 32 bits of a*b)
;
; Byte positions (LSB first):
;   a: a0=R24, a1=R25, a2=R22, a3=R23
;   b: b0=R18, b1=R19, b2=R20, b3=R21
;
; Schoolbook 8x8->16 (MUL) partial products summed into r4:r5:r6:r7, keeping only the
; low four bytes (products that land entirely above byte 3 are dropped). MUL clobbers R1,
; so carry propagation uses a dedicated zero register R8 (cleared once) rather than R1.
; R4-R8 are saved/restored; R0/R1 are scratch (R1 restored to 0).
; -----------------------------------------------------------------------------

__mul32:
    push r4
    push r5
    push r6
    push r7
    push r8
    clr r4
    clr r5
    clr r6
    clr r7
    clr r8                 ; zero register for carry-only adds (R1 is busy with MUL)

    ; offset 0 -> bytes 0,1 (carry to 2,3)
    mul r24, r18           ; a0*b0
    add r4, r0
    adc r5, r1
    adc r6, r8
    adc r7, r8

    ; offset 1 -> bytes 1,2 (carry to 3)
    mul r24, r19           ; a0*b1
    add r5, r0
    adc r6, r1
    adc r7, r8
    mul r25, r18           ; a1*b0
    add r5, r0
    adc r6, r1
    adc r7, r8

    ; offset 2 -> bytes 2,3
    mul r24, r20           ; a0*b2
    add r6, r0
    adc r7, r1
    mul r25, r19           ; a1*b1
    add r6, r0
    adc r7, r1
    mul r22, r18           ; a2*b0
    add r6, r0
    adc r7, r1

    ; offset 3 -> byte 3 (low half only; high half overflows 32 bits)
    mul r24, r21           ; a0*b3
    add r7, r0
    mul r25, r20           ; a1*b2
    add r7, r0
    mul r22, r19           ; a2*b1
    add r7, r0
    mul r23, r18           ; a3*b0
    add r7, r0

    clr r1                 ; restore the zero register
    mov r24, r4            ; result -> output registers
    mov r25, r5
    mov r22, r6
    mov r23, r7
    pop r8
    pop r7
    pop r6
    pop r5
    pop r4
    ret


__bad_interrupt:
	JMP	main

delay_1ms_avr_16mhz:
    PUSH R24
    PUSH R25
    LDI R24, 24
_dly_o16mhz:
    LDI R25, 221
_dly_i16mhz:
    DEC R25
    BRNE _dly_i16mhz
    DEC R24
    BRNE _dly_o16mhz
    POP R25
    POP R24
	RET
pymcu_time__delay_ms_avr:
	STD	Y+44, R24
	STD	Y+45, R25
	LDI	R24, 0
	LDI	R25, 0
	MOV	R4, R24
	MOV	R5, R25
L_0:
	MOV	R24, R4
	MOV	R25, R5
	LDD	R18, Y+44
	LDD	R19, Y+45
	CP	R24, R18
	CPC	R25, R19
	BRSH	L_1
	CALL	delay_1ms_avr_16mhz
	MOV	R24, R4
	MOV	R25, R5
	ADIW	R24, 1
	MOV	R4, R24
	MOV	R5, R25
	JMP	L_0
L_1:
	RET
pymcu_random_randomSeed:
	STD	Y+44, R24
	STD	Y+45, R25
	STD	Y+46, R22
	STD	Y+47, R23

	STD	Y+0, R24
	STD	Y+1, R25
	STD	Y+2, R22
	STD	Y+3, R23
	RET
pymcu_random_random:
	STD	Y+44, R24
	STD	Y+45, R25
	LDD	R24, Y+0
	LDD	R25, Y+1
	LDD	R22, Y+2
	LDD	R23, Y+3
	LDI	R18, 13
	LDI	R19, 102
	LDI	R20, 25
	LDI	R21, 0
	CALL	__mul32
	CLR	R1
	STD	Y+46, R24
	STD	Y+47, R25
	STD	Y+48, R22
	STD	Y+49, R23
	SUBI	R24, 161
	SBCI	R25, 12
	SBCI	R22, 145
	SBCI	R23, 195
	STD	Y+0, R24
	STD	Y+1, R25
	STD	Y+2, R22
	STD	Y+3, R23
	MOV	R24, R22
	MOV	R25, R23
	CLR	R22
	CLR	R23
	STD	Y+50, R24
	STD	Y+51, R25
	STD	Y+52, R22
	STD	Y+53, R23
	LDD	R24, Y+44
	LDD	R25, Y+45
	OR	R24, R25
	BRNE	L_10
	LDI	R22, 6
	SET
	RET
L_10:
	LDD	R24, Y+50
	LDD	R25, Y+51
	LDD	R22, Y+52
	LDD	R23, Y+53
	LDD	R18, Y+44
	LDD	R19, Y+45
	CLR	R20
	CLR	R21
	CALL	__mod32
	STD	Y+54, R24
	STD	Y+55, R25
	STD	Y+56, R22
	STD	Y+57, R23
	CLT
	RET
_s4e65a6dd:
	STD	Y+44, R24
	STD	Y+45, R25
	LDI	R24, 0
	MOV	R6, R24
	LDD	R30, Y+44
	LDD	R31, Y+45
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+47, R24
L_165:
	LDD	R24, Y+47
	CPI	R24, 0
	BREQ	L_166
L_168:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_168
	LDD	R24, Y+47
	STS	0x00C6, R24
	INC	R6
	LDD	R30, Y+44
	LDD	R31, Y+45
	MOV	R24, R6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+47, R24
	JMP	L_165
L_166:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)
	LDI	R26, lo8(_stack_base)
	LDI	R27, hi8(_stack_base)
	LDI	R30, lo8(_bss_end)
	LDI	R31, hi8(_bss_end)
	CP	R26, R30
	CPC	R27, R31
	BREQ	L_BSS_END_5
L_BSS_LOOP_4:
	ST	X+, R1
	CP	R26, R30
	CPC	R27, R31
	BRNE	L_BSS_LOOP_4
L_BSS_END_5:

	SBI	0x04, 5

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 64
	STS	0x007C, R24
	LDI	R24, 135
	STS	0x007A, R24

	LDS	R24, 0x007A
	ORI	R24, 64
	STS	0x007A, R24
L_237:
	LDS	R24, 0x007A
	ANDI	R24, 64
	BRNE	L_237
	LDS	R24, 0x0078
	MOV	R10, R24
	LDS	R24, 0x0079
	MOV	R9, R24
	CLR	R25
	CLR	R22
	CLR	R23
	MOV	R25, R24
	CLR	R24
	STD	Y+6, R24
	STD	Y+7, R25
	STD	Y+8, R22
	STD	Y+9, R23
	MOV	R24, R10
	CLR	R25
	LDD	R18, Y+6
	LDD	R19, Y+7
	ADD	R24, R18
	ADC	R25, R19
	MOV	R11, R24
	MOV	R12, R25

	CLR	R22
	CLR	R23
	STD	Y+12, R24
	STD	Y+13, R25
	STD	Y+14, R22
	STD	Y+15, R23
	CALL	pymcu_random_randomSeed

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd

L_240:

	LDI	R24, 0
	LDI	R25, 1
	CALL	pymcu_random_random
	MOV	R16, R24
	MOV	R17, R25
	BRTC	L_BR_SKIP_7
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_7:
	MOV	R24, R16
	MOV	R25, R17
	MOV	R7, R24
	MOV	R8, R25
	CLR	R22
	CLR	R23
	STD	Y+20, R24
	STD	Y+21, R25
	STD	Y+22, R22
	STD	Y+23, R23
	LDI	R18, 194
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CALL	__mul32
	CLR	R1
	STD	Y+24, R24
	STD	Y+25, R25
	STD	Y+26, R22
	STD	Y+27, R23
	LDI	R18, 255
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CALL	__div32
	STD	Y+28, R24
	STD	Y+29, R25
	STD	Y+30, R22
	STD	Y+31, R23
	ADIW	R24, 50
	MOV	R16, R24
	MOV	R17, R25
	STD	Y+34, R24
	STD	Y+35, R25

	LDI	R24, 44
	LDI	R25, 1
	CALL	pymcu_random_random
	MOV	R16, R24
	MOV	R17, R25
	BRTC	L_BR_SKIP_8
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_8:
	MOV	R24, R16
	MOV	R25, R17
	MOV	R2, R24
	MOV	R3, R25
	CPI	R24, 50
	CPC	R25, R1
	BRSH	L_244
	LDI	R24, 50
	LDI	R25, 0
	MOV	R16, R24
	MOV	R17, R25
	JMP	L_243
L_244:
	MOV	R24, R2
	MOV	R25, R3
	LDI	R18, 45
	LDI	R19, 1
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_245
	LDI	R24, 44
	LDI	R25, 1
	MOV	R16, R24
	MOV	R17, R25
	JMP	L_243
L_245:
	MOV	R24, R2
	MOV	R25, R3
	MOV	R16, R24
	MOV	R17, R25
L_243:
	MOV	R13, R16
	MOV	R14, R17

	SBI	0x05, 5

	LDD	R24, Y+34
	LDD	R25, Y+35
	CALL	pymcu_time__delay_ms_avr

	CBI	0x05, 5

	MOV	R24, R13
	MOV	R25, R14
	CALL	pymcu_time__delay_ms_avr
	JMP	L_240

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 114, 97, 110, 100, 111, 109, 45, 108, 101, 100, 32, 115, 116, 97, 114, 116, 10, 0
.balign 2
	.balign 2
; ── Exception runtime ──────────────────────────────────────────────────────
__exn_str_6:
    .byte 69, 58, 69, 120, 99, 101, 112, 116, 105, 111, 110, 54, 13, 10, 0
.balign 2
    .balign 2

__pymcu_unhandled_exn:
    lds   R16, 0xC1
    sbrs  R16, 3
    rjmp  __exn_halt
    ldi   R30, lo8(__exn_str_6)
    ldi   R31, hi8(__exn_str_6)
__exn_print_loop:
    lpm   R16, Z+
    tst   R16
    breq  __exn_halt
__exn_wait_udre:
    lds   R17, 0xC0
    sbrs  R17, 5
    rjmp  __exn_wait_udre
    sts   0xC6, R16
    rjmp  __exn_print_loop
__exn_halt:
    cli
    rjmp  .-2

