; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_89, _stack_base + 0
.equ tmp_93, _stack_base + 2
.equ _s610f894f, _stack_base + 7
.equ __pymcu_outline_3_v1, _stack_base + 8
.equ __pymcu_outline_3_v4, _stack_base + 11
.equ __pymcu_outline_3_v5, _stack_base + 13
.equ __pymcu_outline_3_v6, _stack_base + 15
.equ __pymcu_outline_3_v7, _stack_base + 19
.equ __pymcu_outline_3_v8, _stack_base + 21
.equ __pymcu_outline_3_v9, _stack_base + 23

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+7, R24
	STD	Y+8, R25
	LDI	R24, 0
	MOV	R4, R24
	LDD	R30, Y+7
	LDD	R31, Y+8
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R11, R24
L_154:
	MOV	R24, R11
	CPI	R24, 0
	BREQ	L_155
	CALL	__pymcu_outline_0
	INC	R4
	LDD	R30, Y+7
	LDD	R31, Y+8
	MOV	R24, R4
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R11, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_1

	SBI	0x04, 5

	SBI	0x05, 5

	NOP
	SBIS	0x03, 5
	JMP	L_BIT_FALSE_1
	LDI	R24, 1
	JMP	L_BIT_DONE_2
L_BIT_FALSE_1:
	LDI	R24, 0
L_BIT_DONE_2:
	MOV	R10, R24

	CBI	0x05, 5

	LDI	R24, 65
	CALL	__pymcu_outline_1

	LDI	R24, 58
	CALL	__pymcu_outline_1

	LDI	R24, 48
	LDI	R25, 0
	MOV	R18, R10
	CLR	R19
	ADD	R24, R18
	ADC	R25, R19
	CALL	__pymcu_outline_2

	LDI	R24, 10
	CALL	__pymcu_outline_1

	LDI	R24, 171
	MOV	R7, R24

	LDI	R24, 66
	CALL	__pymcu_outline_1

	LDI	R24, 58
	CALL	__pymcu_outline_1

	MOV	R24, R7
	CALL	__pymcu_outline_3

	LDI	R24, 10
	CALL	__pymcu_outline_1


	LDI	R24, 18
	MOV	R8, R24

	LDI	R24, 52
	MOV	R9, R24

	LDI	R24, 67
	CALL	__pymcu_outline_1

	LDI	R24, 58
	CALL	__pymcu_outline_1

	MOV	R24, R8
	CALL	__pymcu_outline_3

	MOV	R24, R9
	CALL	__pymcu_outline_3

	LDI	R24, 10
	CALL	__pymcu_outline_1

L_330:
	JMP	L_330
__pymcu_outline_0:
	MOV	R12, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R12
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
	MOV	R13, R24
__pymcu_outline_1.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_1.L0
	MOV	R24, R13
	STS	0x00C6, R24
	RET
__pymcu_outline_2:
	MOV	R14, R24
	MOV	R15, R25
	MOV	R5, R24
	CALL	__pymcu_outline_0
	RET
__pymcu_outline_3:
	MOV	R6, R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 15
	MOV	R2, R24
	MOV	R24, R6
	ANDI	R24, 15
	MOV	R3, R24
	MOV	R24, R2
	CPI	R24, 10
	BRSH	__pymcu_outline_3.L0
	CLR	R25
	ADIW	R24, 48
	CALL	__pymcu_outline_2
	JMP	__pymcu_outline_3.L1
__pymcu_outline_3.L0:
	MOV	R24, R2
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+15, R24
	STD	Y+16, R25
	STD	Y+17, R22
	STD	Y+18, R23
	CALL	__pymcu_outline_2
__pymcu_outline_3.L1:
	MOV	R24, R3
	CPI	R24, 10
	BRSH	__pymcu_outline_3.L2
	CLR	R25
	ADIW	R24, 48
	CALL	__pymcu_outline_2
	JMP	__pymcu_outline_3.L3
__pymcu_outline_3.L2:
	MOV	R24, R3
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+23, R24
	STD	Y+24, R25
	STD	Y+25, R22
	STD	Y+26, R23
	CALL	__pymcu_outline_2
__pymcu_outline_3.L3:
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 73, 90, 0
.balign 2
	.balign 2
