; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_97, _stack_base + 3
.equ tmp_99, _stack_base + 4
.equ tmp_101, _stack_base + 6

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 0

	SBI	0x04, 1

	SBI	0x04, 2

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 1
	MOV	R2, R24

L_264:

	CBI	0x05, 2

	LDI	R24, 7
	MOV	R3, R24

L_267:
	MOV	R24, R3
	CPI	R24, 8
	BRSH	L_268

	MOV	R24, R2
	MOV	R18, R3
L_SHIFT_START_1:
	TST	R18
	BREQ	L_SHIFT_DONE_2
	LSR	R24
	DEC	R18
	JMP	L_SHIFT_START_1
L_SHIFT_DONE_2:
	MOV	R7, R24

	ANDI	R24, 1
	TST	R24
	BREQ	L_270

	SBI	0x05, 0
	JMP	L_269
L_270:

	CBI	0x05, 0
L_269:

	SBI	0x05, 1

	CBI	0x05, 1

	DEC	R3
	MOV	R24, R3
	JMP	L_267
L_268:

	SBI	0x05, 2

L_278:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_278
	MOV	R24, R2
	STS	0x00C6, R24

	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 1
	MOV	R6, R24

	MOV	R24, R2
	CLR	R25
	LSL	R24
	ROL	R25
	MOV	R18, R6
	CLR	R19
	OR	R24, R18
	OR	R25, R19
	MOV	R2, R24

	LDI	R18, 128
	LDI	R19, 26
	LDI	R20, 6
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	JMP	L_264
