; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 4

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+4, R24
	STD	Y+5, R25
	LDI	R24, 0
	MOV	R8, R24
	LDD	R30, Y+4
	LDD	R31, Y+5
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R9, R24
L_164:
	MOV	R24, R9
	CPI	R24, 0
	BREQ	L_165
L_167:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_167
	MOV	R24, R9
	STS	0x00C6, R24
	INC	R8
	LDD	R30, Y+4
	LDD	R31, Y+5
	MOV	R24, R8
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R9, R24
	JMP	L_164
L_165:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	SBI	0x0A, 6
	LDI	R24, 0
	OUT	0x27, R24
	LDI	R24, 131
	OUT	0x24, R24
	LDI	R24, 3
	OUT	0x25, R24

	OUT	0x25, R24

	SBI	0x04, 3
	LDI	R24, 128
	STS	0x00B3, R24
	LDI	R24, 131
	STS	0x00B0, R24
	LDI	R24, 4
	STS	0x00B1, R24

	STS	0x00B1, R24

	SBI	0x04, 1
	LDI	R24, 64
	STS	0x0088, R24
	LDI	R24, 130
	STS	0x0080, R24
	LDI	R24, 10
	STS	0x0081, R24

	STS	0x0081, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_292:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_292
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 0
	MOV	R5, R24

	LDI	R24, 128
	MOV	R6, R24

	LDI	R24, 64
	MOV	R7, R24

	LDI	R24, 0
	MOV	R4, R24

L_294:

	MOV	R24, R5
	OUT	0x27, R24

	MOV	R24, R6
	STS	0x00B3, R24

	MOV	R24, R7
	STS	0x0088, R24

	LDI	R18, 21
	LDI	R19, 52
	LDI	R20, 0
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0

	INC	R5

	INC	R6

	INC	R7

	INC	R4
	MOV	R24, R4

	CPI	R24, 0
	BRNE	L_300

L_303:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_303
	LDI	R24, 68
	STS	0x00C6, R24

L_307:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_307
	LDI	R24, 10
	STS	0x00C6, R24
L_300:
	JMP	L_294

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 80, 87, 77, 51, 0
.balign 2
	.balign 2
