; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_131, _stack_base + 0
.equ main_humidity, _stack_base + 4
.equ main_temperature, _stack_base + 5
.equ tmp_137, _stack_base + 6
.equ tmp_138, _stack_base + 7
.equ _s610f894f, _stack_base + 8
.equ _s5b0f7fdd, _stack_base + 10
.equ _s500f6e8c, _stack_base + 11
.equ pd_read_bit, _stack_base + 8
.equ tmp_95, _stack_base + 10
.equ tmp_98, _stack_base + 11
.equ tmp_101, _stack_base + 14
.equ tmp_104, _stack_base + 15
.equ pd_read_hum_int, _stack_base + 16
.equ pd_read_hum_dec, _stack_base + 17
.equ pd_read_temp_int, _stack_base + 18
.equ pd_read_temp_dec, _stack_base + 19
.equ pd_read_chksum, _stack_base + 20
.equ tmp_112, _stack_base + 21
.equ tmp_113, _stack_base + 23
.equ pd_read_expected, _stack_base + 27
.equ tmp_116, _stack_base + 30
.equ delay_ms_avr_ms, _stack_base + 34
.equ delay_us_avr_us, _stack_base + 34
.equ pd_byte_mask, _stack_base + 34
.equ tmp_118, _stack_base + 39
.equ tmp_121, _stack_base + 40
.equ tmp_124, _stack_base + 42
.equ _s4411586d, _stack_base + 9
.equ _s9a9c4219, _stack_base + 10
.equ _s8efc29b1, _stack_base + 11
.equ tmp_8, _stack_base + 12
.equ inline1_uart_write_data, _stack_base + 14

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4c1d799f:
	MOV	R5, R24
	LDI	R24, 0
	STD	Y+9, R24
	MOV	R24, R5
	CPI	R24, 100
	BRLO	L_10
	LDI	R24, 48
	STD	Y+10, R24
L_11:
	MOV	R24, R5
	CPI	R24, 100
	BRLO	L_12
	SUBI	R24, 100
	MOV	R5, R24
	LDD	R24, Y+10
	INC	R24
	STD	Y+10, R24
	JMP	L_11
L_12:
L_14:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_14
	LDD	R24, Y+10
	STS	0x00C6, R24
	LDI	R24, 1
	STD	Y+9, R24
L_10:
	MOV	R24, R5
	CPI	R24, 10
	BRSH	L_17
	LDD	R24, Y+9
	CPI	R24, 1
	BRNE	L_16
L_17:
	LDI	R24, 48
	STD	Y+11, R24
L_18:
	MOV	R24, R5
	CPI	R24, 10
	BRLO	L_19
	SUBI	R24, 10
	MOV	R5, R24
	LDD	R24, Y+11
	INC	R24
	STD	Y+11, R24
	JMP	L_18
L_19:
L_21:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_21
	LDD	R24, Y+11
	STS	0x00C6, R24
L_16:
	MOV	R24, R5
	CLR	R25
	ADIW	R24, 48
	STD	Y+14, R24
L_24:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_24
	LDD	R24, Y+14
	STS	0x00C6, R24
	RET
_s4e65a6dd:
	STD	Y+8, R24
	STD	Y+9, R25
	LDI	R24, 0
	STD	Y+10, R24
	LDD	R30, Y+8
	LDD	R31, Y+9
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+11, R24
L_164:
	LDD	R24, Y+11
	CPI	R24, 0
	BREQ	L_165
L_167:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_167
	LDD	R24, Y+11
	STS	0x00C6, R24
	LDD	R24, Y+10
	INC	R24
	STD	Y+10, R24
	LDD	R30, Y+8
	LDD	R31, Y+9
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+11, R24
	JMP	L_164
L_165:
	RET
pd_read:
	STD	Y+8, R24

	LDI	R24, 1
	LDD	R18, Y+8
L_SHIFT_START_10:
	TST	R18
	BREQ	L_SHIFT_DONE_11
	LSL	R24
	DEC	R18
	JMP	L_SHIFT_START_10
L_SHIFT_DONE_11:
	MOV	R3, R24

	IN	R24, 0x0A
	OR	R24, R3
	OUT	0x0A, R24

	MOV	R24, R3
	COM	R24
	MOV	R16, R24
	IN	R24, 0x0B
	AND	R24, R16
	OUT	0x0B, R24

	LDI	R18, 128
	LDI	R19, 187
	LDI	R20, 0
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0

	MOV	R24, R3
	COM	R24
	MOV	R16, R24
	IN	R24, 0x0A
	AND	R24, R16
	OUT	0x0A, R24

	IN	R24, 0x0B
	OR	R24, R3
	OUT	0x0B, R24

	LDI	R18, 106
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
_dly_L1:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L1

	LDI	R24, 255
	MOV	R2, R24
L_198:
	MOV	R24, R2
	CPI	R24, 1
	BRLO	L_199
	IN	R24, 0x09
	AND	R24, R3
	MOV	R4, R24
	CPI	R24, 0
	BRNE	L_202
	MOV	R24, R2
	MOV	R16, R24
	JMP	L_197
L_202:
	DEC	R2
	JMP	L_198
L_199:
	LDI	R24, 0
	MOV	R16, R24
L_197:
	MOV	R24, R16
	CPI	R24, 0
	BRNE	L_196

	LDI	R24, 255
	LDI	R25, 255
	RET
L_196:

	LDI	R24, 255
	MOV	R2, R24
L_205:
	MOV	R24, R2
	CPI	R24, 1
	BRLO	L_206
	IN	R24, 0x09
	AND	R24, R3
	MOV	R4, R24
	TST	R24
	BREQ	L_209
	MOV	R24, R2
	MOV	R16, R24
	JMP	L_204
L_209:
	DEC	R2
	JMP	L_205
L_206:
	LDI	R24, 0
	MOV	R16, R24
L_204:
	MOV	R24, R16
	CPI	R24, 0
	BRNE	L_203

	LDI	R24, 255
	LDI	R25, 255
	RET
L_203:

	MOV	R24, R3
	CALL	pd_byte
	STD	Y+16, R24

	MOV	R24, R3
	CALL	pd_byte
	STD	Y+17, R24

	MOV	R24, R3
	CALL	pd_byte
	STD	Y+18, R24

	MOV	R24, R3
	CALL	pd_byte
	STD	Y+19, R24

	MOV	R24, R3
	CALL	pd_byte
	STD	Y+20, R24

	LDD	R24, Y+16
	CLR	R25
	LDD	R18, Y+17
	CLR	R19
	ADD	R24, R18
	ADC	R25, R19
	CLR	R22
	CLR	R23
	LDD	R18, Y+18
	CLR	R19
	CLR	R20
	CLR	R21
	ADD	R24, R18
	ADC	R25, R19
	ADC	R22, R20
	ADC	R23, R21
	STD	Y+23, R24
	STD	Y+24, R25
	STD	Y+25, R22
	STD	Y+26, R23
	LDD	R18, Y+19
	ADD	R24, R18
	STD	Y+27, R24

	LDD	R24, Y+20
	LDD	R18, Y+27
	CP	R24, R18
	BREQ	L_210
	LDI	R24, 255
	LDI	R25, 255
	RET
L_210:
	LDD	R24, Y+16
	CLR	R25
	CLR	R22
	CLR	R23
	MOV	R25, R24
	CLR	R24
	STD	Y+30, R24
	STD	Y+31, R25
	STD	Y+32, R22
	STD	Y+33, R23
	LDD	R18, Y+18
	CLR	R19
	CLR	R20
	CLR	R21
	OR	R24, R18
	OR	R25, R19
	OR	R22, R20
	OR	R23, R21
	MOV	R11, R24
	MOV	R12, R25
	RET
pd_byte:
	STD	Y+34, R24
	LDI	R24, 0
	MOV	R6, R24
	MOV	R10, R24
L_211:
	MOV	R24, R10
	CPI	R24, 8
	BRLO	L_BR_SKIP_20
	JMP	L_212
L_BR_SKIP_20:
	LDI	R24, 255
	MOV	R2, R24
L_215:
	MOV	R24, R2
	CPI	R24, 1
	BRLO	L_216
	IN	R24, 0x09
	LDD	R18, Y+34
	AND	R24, R18
	MOV	R4, R24
	CPI	R24, 0
	BRNE	L_219
	MOV	R24, R2
	MOV	R16, R24
	JMP	L_214
L_219:
	DEC	R2
	JMP	L_215
L_216:
	LDI	R24, 0
	MOV	R16, R24
L_214:
	MOV	R24, R16
	CPI	R24, 0
	BRNE	L_213
	LDI	R24, 0
	RET
L_213:
	LDI	R24, 255
	MOV	R2, R24
L_222:
	MOV	R24, R2
	CPI	R24, 1
	BRLO	L_223
	IN	R24, 0x09
	LDD	R18, Y+34
	AND	R24, R18
	MOV	R4, R24
	TST	R24
	BREQ	L_226
	MOV	R24, R2
	MOV	R16, R24
	JMP	L_221
L_226:
	DEC	R2
	JMP	L_222
L_223:
	LDI	R24, 0
	MOV	R16, R24
L_221:
	MOV	R24, R16
	CPI	R24, 0
	BRNE	L_220
	LDI	R24, 0
	RET
L_220:
	LDI	R24, 0
	MOV	R7, R24
L_227:
	IN	R24, 0x09
	LDD	R18, Y+34
	AND	R24, R18
	TST	R24
	BREQ	L_228
	INC	R7
	MOV	R24, R7
	CPI	R24, 255
	BREQ	L_228
	JMP	L_227
L_228:
	MOV	R24, R6
	LSL	R24
	MOV	R6, R24
	MOV	R24, R7
	CPI	R24, 65
	BRLO	L_230
	MOV	R24, R6
	ORI	R24, 1
	MOV	R6, R24
L_230:
	INC	R10
	JMP	L_211
L_212:
	MOV	R24, R6
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	SBI	0x04, 5


	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd

L_260:

	LDI	R24, 2
	CALL	pd_read
	MOV	R8, R24
	MOV	R9, R25

	LDI	R18, 255
	LDI	R19, 255
	CP	R24, R18
	CPC	R25, R19
	BRNE	L_267

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd
	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd

	CBI	0x05, 5
	JMP	L_266
L_267:

	MOV	R24, R9
	CLR	R25
	STD	Y+4, R24

	MOV	R24, R8
	STD	Y+5, R24

	LDI	R24, lo8(__flash___cstr_3)
	LDI	R25, hi8(__flash___cstr_3)
	CALL	_s4e65a6dd
	LDD	R24, Y+4
	CALL	_s4c1d799f
	LDI	R24, lo8(__flash___cstr_4)
	LDI	R25, hi8(__flash___cstr_4)
	CALL	_s4e65a6dd
	LDD	R24, Y+5
	CALL	_s4c1d799f
	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd

	SBI	0x05, 5
L_266:

	LDI	R18, 85
	LDI	R19, 97
	LDI	R20, 81
	LDI	R21, 0
_dly_L2:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L2
	JMP	L_260

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 68, 72, 84, 49, 49, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 10, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 69, 82, 82, 0
.balign 2
	.balign 2
__flash___cstr_3:
	.byte 72, 58, 0
.balign 2
	.balign 2
__flash___cstr_4:
	.byte 32, 84, 58, 0
.balign 2
	.balign 2
