; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_89, _stack_base + 1
.equ tmp_92, _stack_base + 2
.equ tmp_95, _stack_base + 5
.equ tmp_97, _stack_base + 8
.equ tmp_98, _stack_base + 10
.equ tmp_100, _stack_base + 14
.equ tmp_102, _stack_base + 16
.equ tmp_103, _stack_base + 18
.equ _s610f894f, _stack_base + 22

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_sb2da76ff:
	MOV	R11, R24
	OUT	0x2E, R24
L_0:
	IN	R24, 0x2D
	ANDI	R24, 128
	BREQ	L_0
	IN	R24, 0x2E
	MOV	R7, R24
	RET
_s4e65a6dd:
	STD	Y+22, R24
	STD	Y+23, R25
	LDI	R24, 0
	MOV	R6, R24
	LDD	R30, Y+22
	LDD	R31, Y+23
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
L_156:
	MOV	R24, R8
	CPI	R24, 0
	BREQ	L_157
	CALL	__pymcu_outline_0
	INC	R6
	LDD	R30, Y+22
	LDD	R31, Y+23
	MOV	R24, R6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
	JMP	L_156
L_157:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	SBI	0x04, 3
	SBI	0x04, 5
	SBI	0x04, 2
	SBI	0x05, 2
	LDI	R24, 80
	OUT	0x2C, R24
	SBI	0x04, 0
	SBI	0x05, 0

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_1

	LDI	R24, 165
	MOV	R5, R24

	CBI	0x05, 0

	CALL	_sb2da76ff
	SBI	0x05, 0

	LDI	R24, 68
	CALL	__pymcu_outline_1

	LDI	R24, 58
	CALL	__pymcu_outline_1

	MOV	R24, R5
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 15
	MOV	R3, R24
	MOV	R24, R5
	ANDI	R24, 15
	MOV	R4, R24
	MOV	R24, R3
	CPI	R24, 10
	BRSH	L_244
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_243
L_244:
	MOV	R24, R3
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+10, R24
	STD	Y+11, R25
	STD	Y+12, R22
	STD	Y+13, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_243:
	MOV	R24, R4
	CPI	R24, 10
	BRSH	L_254
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_253
L_254:
	MOV	R24, R4
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+18, R24
	STD	Y+19, R25
	STD	Y+20, R22
	STD	Y+21, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_253:

	LDI	R24, 10
	CALL	__pymcu_outline_1

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_1

L_273:
	JMP	L_273
__pymcu_outline_0:
	MOV	R9, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R9
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
	MOV	R10, R24
__pymcu_outline_1.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_1.L0
	MOV	R24, R10
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 83, 67, 83, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 79, 75, 0
.balign 2
	.balign 2
