; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s398e6324, _stack_base + 0
.equ tmp_127, _stack_base + 4
.equ tmp_133, _stack_base + 12
.equ main_temp_hi, _stack_base + 16
.equ main_temp_lo, _stack_base + 17
.equ main_press_hi, _stack_base + 18
.equ main_press_lo, _stack_base + 19
.equ _s610f894f, _stack_base + 20
.equ _s500f6e8c, _stack_base + 23
.equ __pymcu_outline_0_p0, _stack_base + 43
.equ __pymcu_outline_1_p0, _stack_base + 20
.equ bmp280_write_addr, _stack_base + 20
.equ bmp280_write_reg, _stack_base + 21
.equ bmp280_write_val, _stack_base + 22
.equ tmp_99, _stack_base + 23
.equ tmp_100, _stack_base + 24
.equ tmp_102, _stack_base + 26
.equ tmp_103, _stack_base + 27
.equ tmp_104, _stack_base + 28
.equ tmp_105, _stack_base + 29
.equ _s4c542d43, _stack_base + 36
.equ _s6ac07b50, _stack_base + 36
.equ _s938848aa, _stack_base + 37
.equ delay_ms_avr_ms, _stack_base + 20
.equ bmp280_read_addr, _stack_base + 20
.equ bmp280_read_reg, _stack_base + 21
.equ tmp_106, _stack_base + 22
.equ tmp_107, _stack_base + 23
.equ tmp_109, _stack_base + 25
.equ tmp_110, _stack_base + 26
.equ tmp_111, _stack_base + 27
.equ tmp_112, _stack_base + 28
.equ tmp_113, _stack_base + 29
.equ tmp_114, _stack_base + 31
.equ tmp_116, _stack_base + 33
.equ tmp_117, _stack_base + 34
.equ bmp280_read_result, _stack_base + 35
.equ _s05d9dd22, _stack_base + 36
.equ __pymcu_outline_3_v1, _stack_base + 21
.equ __pymcu_outline_3_v4, _stack_base + 24
.equ __pymcu_outline_3_v5, _stack_base + 26
.equ __pymcu_outline_3_v6, _stack_base + 28
.equ __pymcu_outline_3_v7, _stack_base + 32
.equ __pymcu_outline_3_v8, _stack_base + 34
.equ __pymcu_outline_3_v9, _stack_base + 36
.equ __pymcu_outline_2_p0, _stack_base + 40

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+20, R24
	STD	Y+21, R25
	LDI	R24, 0
	MOV	R10, R24
	LDD	R30, Y+20
	LDD	R31, Y+21
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+23, R24
L_164:
	LDD	R24, Y+23
	CPI	R24, 0
	BREQ	L_165
	LDD	R24, Y+23
	CALL	__pymcu_outline_0
	INC	R10
	LDD	R30, Y+20
	LDD	R31, Y+21
	MOV	R24, R10
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+23, R24
	JMP	L_164
L_165:
	RET
_s9c096ac4:
	LDI	R24, 164
	STS	0x00BC, R24
L_194:
	LDS	R24, 0x00BC
	ANDI	R24, 128
	BREQ	L_194
	LDS	R24, 0x00B9
	ANDI	R24, 248
	STD	Y+36, R24
	RET
_s8b5d0640:
	LDI	R24, 148
	STS	0x00BC, R24
	RET
_s4cb7a3c7:
	STD	Y+36, R24
	STS	0x00BB, R24
	LDI	R24, 132
	STS	0x00BC, R24
L_196:
	LDS	R24, 0x00BC
	ANDI	R24, 128
	BREQ	L_196
	LDS	R24, 0x00B9
	ANDI	R24, 248
	STD	Y+37, R24
	RET
_s6709a002:
	LDI	R24, 132
	STS	0x00BC, R24
L_200:
	LDS	R24, 0x00BC
	ANDI	R24, 128
	BREQ	L_200
	LDS	R24, 0x00BB
	STD	Y+36, R24
	RET
bmp280_write:
	STD	Y+20, R24
	STD	Y+21, R22
	STD	Y+22, R20

	CALL	_s9c096ac4

	LDD	R24, Y+20
	CLR	R25
	LSL	R24
	ROL	R25
	LDI	R18, 254
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	STD	Y+26, R24
	CALL	_s4cb7a3c7

	LDD	R24, Y+21
	CALL	_s4cb7a3c7

	LDD	R24, Y+22
	CALL	_s4cb7a3c7

	CALL	_s8b5d0640
	RET
bmp280_read:
	STD	Y+20, R24
	STD	Y+21, R22

	CALL	_s9c096ac4

	LDD	R24, Y+20
	CLR	R25
	LSL	R24
	ROL	R25
	LDI	R18, 254
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	STD	Y+25, R24
	CALL	_s4cb7a3c7

	LDD	R24, Y+21
	CALL	_s4cb7a3c7

	CALL	_s9c096ac4

	LDD	R24, Y+20
	CLR	R25
	LSL	R24
	ROL	R25
	LDI	R18, 254
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	STD	Y+31, R24
	STD	Y+32, R25
	LDI	R18, 1
	OR	R24, R18
	OR	R25, R19
	CALL	_s4cb7a3c7

	CALL	_s6709a002
	STD	Y+35, R24

	CALL	_s8b5d0640

	LDD	R24, Y+35
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 72
	STS	0x00B8, R24
	LDI	R24, 4
	STS	0x00BC, R24


	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_1

	LDI	R24, 118
	LDI	R22, 244
	LDI	R20, 39
	CALL	bmp280_write
	LDI	R24, 118
	LDI	R22, 245
	LDI	R20, 0
	CALL	bmp280_write

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_1

	LDI	R18, 42
	LDI	R19, 104
	LDI	R20, 0
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0

	LDI	R24, 118
	LDI	R22, 250
	CALL	bmp280_read
	STD	Y+0, R24
	LDI	R24, 118
	LDI	R22, 251
	CALL	bmp280_read
	MOV	R15, R24
	LDD	R24, Y+0
	CLR	R25
	CLR	R22
	CLR	R23
	MOV	R25, R24
	CLR	R24
	STD	Y+4, R24
	STD	Y+5, R25
	STD	Y+6, R22
	STD	Y+7, R23
	MOV	R18, R15
	CLR	R19
	CLR	R20
	CLR	R21
	OR	R24, R18
	OR	R25, R19
	OR	R22, R20
	OR	R23, R21
	MOV	R4, R24
	MOV	R5, R25

	LDI	R24, 118
	LDI	R22, 247
	CALL	bmp280_read
	MOV	R14, R24
	LDI	R24, 118
	LDI	R22, 248
	CALL	bmp280_read
	MOV	R13, R24
	MOV	R24, R14
	CLR	R25
	CLR	R22
	CLR	R23
	MOV	R25, R24
	CLR	R24
	STD	Y+12, R24
	STD	Y+13, R25
	STD	Y+14, R22
	STD	Y+15, R23
	MOV	R18, R13
	CLR	R19
	CLR	R20
	CLR	R21
	OR	R24, R18
	OR	R25, R19
	OR	R22, R20
	OR	R23, R21
	MOV	R2, R24
	MOV	R3, R25

	MOV	R24, R5
	CLR	R25
	STD	Y+16, R24

	MOV	R24, R4
	STD	Y+17, R24

	LDI	R24, 84
	CALL	__pymcu_outline_1

	LDI	R24, 58
	CALL	__pymcu_outline_1

	LDD	R24, Y+16
	CALL	__pymcu_outline_3

	LDD	R24, Y+17
	CALL	__pymcu_outline_3

	LDI	R24, 10
	CALL	__pymcu_outline_1

	MOV	R24, R3
	CLR	R25
	STD	Y+18, R24

	MOV	R24, R2
	STD	Y+19, R24

	LDI	R24, 80
	CALL	__pymcu_outline_1

	LDI	R24, 58
	CALL	__pymcu_outline_1

	LDD	R24, Y+18
	CALL	__pymcu_outline_3

	LDD	R24, Y+19
	CALL	__pymcu_outline_3

	LDI	R24, 10
	CALL	__pymcu_outline_1

L_338:
	JMP	L_338
__pymcu_outline_0:
	STD	Y+43, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	LDD	R24, Y+43
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
	STD	Y+20, R24
__pymcu_outline_1.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_1.L0
	LDD	R24, Y+20
	STS	0x00C6, R24
	RET
__pymcu_outline_2:
	STD	Y+40, R24
	STD	Y+41, R25
	MOV	R11, R24
	CALL	__pymcu_outline_0
	RET
__pymcu_outline_3:
	MOV	R12, R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 15
	MOV	R6, R24
	MOV	R24, R12
	ANDI	R24, 15
	MOV	R7, R24
	MOV	R24, R6
	CPI	R24, 10
	BRSH	__pymcu_outline_3.L0
	CLR	R25
	ADIW	R24, 48
	CALL	__pymcu_outline_2
	JMP	__pymcu_outline_3.L1
__pymcu_outline_3.L0:
	MOV	R24, R6
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+28, R24
	STD	Y+29, R25
	STD	Y+30, R22
	STD	Y+31, R23
	CALL	__pymcu_outline_2
__pymcu_outline_3.L1:
	MOV	R24, R7
	CPI	R24, 10
	BRSH	__pymcu_outline_3.L2
	CLR	R25
	ADIW	R24, 48
	CALL	__pymcu_outline_2
	JMP	__pymcu_outline_3.L3
__pymcu_outline_3.L2:
	MOV	R24, R7
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+36, R24
	STD	Y+37, R25
	STD	Y+38, R22
	STD	Y+39, R23
	CALL	__pymcu_outline_2
__pymcu_outline_3.L3:
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 66, 77, 80, 50, 56, 48, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 79, 75, 0
.balign 2
	.balign 2
