; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_94, _stack_base + 5
.equ _s610f894f, _stack_base + 6

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+6, R24
	STD	Y+7, R25
	LDI	R24, 0
	MOV	R7, R24
	LDD	R30, Y+6
	LDD	R31, Y+7
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
L_154:
	MOV	R24, R8
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R8
	STS	0x00C6, R24
	INC	R7
	LDD	R30, Y+6
	LDD	R31, Y+7
	MOV	R24, R7
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)





	SBI	0x04, 0
	SBI	0x04, 1
	SBI	0x04, 2

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 0
	OUT	0x24, R24
	LDI	R24, 4
	OUT	0x25, R24

	LDI	R24, 0
	MOV	R2, R24

	LDI	R25, 0
	MOV	R5, R24
	MOV	R6, R25

	LDI	R24, 220
	LDI	R25, 2
	MOV	R3, R24
	MOV	R4, R25

	SBI	0x05, 0
	CBI	0x05, 1
	CBI	0x05, 2

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0

L_282:

	SBIS	0x15, 0
	JMP	L_BIT_FALSE_2
	LDI	R24, 1
	JMP	L_BIT_DONE_3
L_BIT_FALSE_2:
	LDI	R24, 0
L_BIT_DONE_3:
	TST	R24
	BRNE	L_BR_SKIP_4
	JMP	L_284
L_BR_SKIP_4:

	SBI	0x15, 0

	MOV	R24, R5
	MOV	R25, R6
	ADIW	R24, 1
	MOV	R5, R24
	MOV	R6, R25

	MOV	R18, R3
	MOV	R19, R4
	CP	R24, R18
	CPC	R25, R19
	BRSH	L_BR_SKIP_5
	JMP	L_291
L_BR_SKIP_5:

	LDI	R24, 0
	LDI	R25, 0
	MOV	R5, R24
	MOV	R6, R25
	MOV	R24, R2
	CPI	R24, 0
	BRNE	L_293

	LDI	R24, 1
	MOV	R2, R24

	LDI	R24, 244
	LDI	R25, 0
	MOV	R3, R24
	MOV	R4, R25

	SBI	0x05, 0
	SBI	0x05, 1
	CBI	0x05, 2

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_292
L_293:
	MOV	R24, R2
	CPI	R24, 1
	BRNE	L_309

	LDI	R24, 2
	MOV	R2, R24

	LDI	R24, 220
	LDI	R25, 2
	MOV	R3, R24
	MOV	R4, R25

	CBI	0x05, 0
	CBI	0x05, 1
	SBI	0x05, 2

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_292
L_309:
	MOV	R24, R2
	CPI	R24, 2
	BRNE	L_325

	LDI	R24, 3
	MOV	R2, R24

	LDI	R24, 244
	LDI	R25, 0
	MOV	R3, R24
	MOV	R4, R25

	CBI	0x05, 0
	SBI	0x05, 1
	CBI	0x05, 2

	LDI	R24, lo8(__flash___cstr_3)
	LDI	R25, hi8(__flash___cstr_3)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_292
L_325:

	LDI	R24, 0
	MOV	R2, R24

	LDI	R24, 220
	LDI	R25, 2
	MOV	R3, R24
	MOV	R4, R25

	SBI	0x05, 0
	CBI	0x05, 1
	CBI	0x05, 2

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
L_292:
L_291:
L_284:
	JMP	L_282
__pymcu_outline_0:
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	LDI	R24, 10
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 82, 69, 68, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 82, 69, 68, 43, 89, 69, 76, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 71, 82, 69, 69, 78, 0
.balign 2
	.balign 2
__flash___cstr_3:
	.byte 89, 69, 76, 76, 79, 87, 0
.balign 2
	.balign 2
