; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 3
.equ tmp_93, _stack_base + 7
.equ tmp_94, _stack_base + 8
.equ delay_ms_avr_ms, _stack_base + 3

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+3, R24
	STD	Y+4, R25
	LDI	R24, 0
	MOV	R7, R24
	LDD	R30, Y+3
	LDD	R31, Y+4
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R9, R24
L_164:
	MOV	R24, R9
	CPI	R24, 0
	BREQ	L_165
L_167:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_167
	MOV	R24, R9
	STS	0x00C6, R24
	INC	R7
	LDD	R30, Y+3
	LDD	R31, Y+4
	MOV	R24, R7
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R9, R24
	JMP	L_164
L_165:
	RET
_sb2da76ff:
	MOV	R14, R24
	OUT	0x2E, R24
L_194:
	IN	R24, 0x2D
	ANDI	R24, 128
	BREQ	L_194
	IN	R24, 0x2E
	MOV	R8, R24
	RET
_sb13e7676:
	MOV	R12, R24
	MOV	R13, R22

	CALL	_sb2da76ff

	MOV	R24, R13
	CALL	_sb2da76ff
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	SBI	0x04, 3
	SBI	0x04, 5
	SBI	0x04, 2
	SBI	0x05, 2
	LDI	R24, 80
	OUT	0x2C, R24
	SBI	0x04, 2
	SBI	0x05, 2


	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_233:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_233
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 12
	LDI	R22, 1
	CALL	__pymcu_outline_0
	LDI	R24, 9
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 10
	LDI	R22, 8
	CALL	__pymcu_outline_0
	LDI	R24, 11
	LDI	R22, 7
	CALL	__pymcu_outline_0
	LDI	R24, 15
	LDI	R22, 0
	CALL	__pymcu_outline_0

	LDI	R24, 1
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 2
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 3
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 4
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 5
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 6
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 7
	LDI	R22, 0
	CALL	__pymcu_outline_0
	LDI	R24, 8
	LDI	R22, 0
	CALL	__pymcu_outline_0

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
L_332:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_332
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 0
	MOV	R2, R24

	LDI	R24, 170
	MOV	R6, R24

L_334:
	MOV	R24, R2
	CPI	R24, 8
	BRSH	L_335

	INC	R24
	MOV	R3, R24
	CBI	0x05, 2
	MOV	R22, R6
	CALL	_sb13e7676
	SBI	0x05, 2

	MOV	R24, R6
	LDI	R18, 255
	EOR	R24, R18
	MOV	R6, R24

	INC	R2
	MOV	R24, R2
	JMP	L_334
L_335:

	LDI	R24, 10
	LDI	R22, 8
	CALL	__pymcu_outline_0

	LDI	R18, 85
	LDI	R19, 88
	LDI	R20, 20
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0

L_353:

	LDI	R24, 0
	MOV	R2, R24

L_355:
	MOV	R24, R2
	CPI	R24, 8
	BRSH	L_356

	INC	R24
	MOV	R3, R24
	CBI	0x05, 2
	MOV	R22, R2
	CALL	_sb13e7676
	SBI	0x05, 2

	INC	R2
	MOV	R24, R2
	JMP	L_355
L_356:

	LDI	R18, 85
	LDI	R19, 35
	LDI	R20, 8
	LDI	R21, 0
_dly_L1:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L1
	JMP	L_353
__pymcu_outline_0:
	MOV	R10, R24
	MOV	R11, R22
	CBI	0x05, 2
	CALL	_sb13e7676
	SBI	0x05, 2
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 77, 65, 88, 55, 50, 49, 57, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 79, 75, 0
.balign 2
	.balign 2
