; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_9, _stack_base + 4
.equ tone_ocr_half_counts, _stack_base + 8
.equ tmp_7, _stack_base + 12
.equ tmp_14, _stack_base + 13
.equ tmp_12, _stack_base + 17
.equ tmp_19, _stack_base + 18
.equ tmp_17, _stack_base + 22
.equ tmp_24, _stack_base + 23
.equ tmp_22, _stack_base + 27
.equ tmp_29, _stack_base + 28
.equ tmp_27, _stack_base + 32
.equ tmp_34, _stack_base + 33
.equ tmp_32, _stack_base + 37
.equ tmp_39, _stack_base + 38
.equ tmp_37, _stack_base + 42

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt


; --- PyMCU AVR Math Runtime ---
; -----------------------------------------------------------------------------
; PyMCU AVR Math Runtime
; -----------------------------------------------------------------------------
;
; __div32: Unsigned 32-bit Division
;   Input:  R23:R22:R25:R24 (Dividend, MSB..LSB), R21:R20:R19:R18 (Divisor)
;   Output: R23:R22:R25:R24 (Quotient)
;   Clobbers: R4-R7 (remainder), R16 (loop counter)
;   Note: R4-R7 and R16 are saved/restored via PUSH/POP.
;
; __mod32: Unsigned 32-bit Modulo
;   Input:  R23:R22:R25:R24 (Dividend), R21:R20:R19:R18 (Divisor)
;   Output: R23:R22:R25:R24 (Remainder)
;   Clobbers: R4-R7 (intermediate quotient), R16 (loop counter)
;
; Register layout (byte positions, LSB first):
;   byte0 = R24 (dividend / quotient LSB)
;   byte1 = R25
;   byte2 = R22
;   byte3 = R23 (dividend / quotient MSB)
;   divisor LSB = R18, byte1 = R19, byte2 = R20, MSB = R21
;   remainder LSB = R4, byte1 = R5, byte2 = R6, MSB = R7 (local, saved)
;
; Algorithm: Non-restoring bit-by-bit long division (33 iterations).
; -----------------------------------------------------------------------------

; __div32_core: shared inner loop used by both __div32 and __mod32.
;   Pre-condition: R4:R5:R6:R7 = 0 (remainder), R16 = 33 (counter).
;   Post-condition: R23:R22:R25:R24 = Quotient, R7:R6:R5:R4 = Remainder.
;   Does NOT save/restore any registers.
__div32_core:
__div32_core_loop:
    rol r24             ; Shift dividend left (LSB first carries out MSB)
    rol r25
    rol r22
    rol r23
    dec r16
    breq __div32_core_done
    rol r4              ; Shift remainder left, incoming dividend MSB in Carry
    rol r5
    rol r6
    rol r7
    sub r4, r18         ; Remainder -= Divisor
    sbc r5, r19
    sbc r6, r20
    sbc r7, r21
    brcc __div32_core_next  ; No borrow => remainder >= divisor
    add r4, r18         ; Restore remainder
    adc r5, r19
    adc r6, r20
    adc r7, r21
    clc                 ; Quotient bit = 0
    rjmp __div32_core_loop
__div32_core_next:
    sec                 ; Quotient bit = 1
    rjmp __div32_core_loop
__div32_core_done:
    ret

__div32:
    push r4
    push r5
    push r6
    push r7
    push r16
    clr r4
    clr r5
    clr r6
    clr r7
    ldi r16, 33
    rcall __div32_core
    pop r16
    pop r7
    pop r6
    pop r5
    pop r4
    ret

__mod32:
    push r4
    push r5
    push r6
    push r7
    push r16
    clr r4
    clr r5
    clr r6
    clr r7
    ldi r16, 33
    rcall __div32_core
    mov r24, r4         ; Move remainder to result registers
    mov r25, r5
    mov r22, r6
    mov r23, r7
    pop r16
    pop r7
    pop r6
    pop r5
    pop r4
    ret

; -----------------------------------------------------------------------------
; __divs32 / __mods32: SIGNED 32-bit floor division and modulo (Python).
;   Input:  R23:R22:R25:R24 (Dividend a, MSB..LSB), R21:R20:R19:R18 (Divisor b)
;   Output: __divs32 -> R23:R22:R25:R24 = floor(a/b)
;           __mods32 -> R23:R22:R25:R24 = a - b*floor(a/b)   (sign of b)
; Each is self-contained (one __div32_core pass). R4-R13 are saved/restored, so
; the net clobber matches __div32/__mod32 (R4-R7 used internally and restored);
; R16 (counter) and R0 (scratch) are caller-saved. 32-bit in-place negate:
;   com b3 / com b2 / com b1 / neg b0 / sbci b1 / sbci b2 / sbci b3 (each ,0xFF).
; -----------------------------------------------------------------------------
__divs32:
    push r4
    push r5
    push r6
    push r7
    push r8             ; sign(a)
    push r9             ; sign(b)
    mov  r8, r23
    mov  r9, r21
    sbrs r23, 7
    rjmp __divs32_absb
    com  r23            ; |a|
    com  r22
    com  r25
    neg  r24
    sbci r25, 0xFF
    sbci r22, 0xFF
    sbci r23, 0xFF
__divs32_absb:
    sbrs r21, 7
    rjmp __divs32_div
    com  r21            ; |b|
    com  r20
    com  r19
    neg  r18
    sbci r19, 0xFF
    sbci r20, 0xFF
    sbci r21, 0xFF
__divs32_div:
    clr  r4
    clr  r5
    clr  r6
    clr  r7
    ldi  r16, 33
    rcall __div32_core  ; quotient R23:R22:R25:R24 ; remainder R7:R6:R5:R4
    mov  r0, r8
    eor  r0, r9
    sbrs r0, 7
    rjmp __divs32_done  ; signs equal -> trunc quotient == floor
    com  r23            ; negate quotient
    com  r22
    com  r25
    neg  r24
    sbci r25, 0xFF
    sbci r22, 0xFF
    sbci r23, 0xFF
    mov  r0, r4         ; remainder != 0 ?
    or   r0, r5
    or   r0, r6
    or   r0, r7
    breq __divs32_done
    subi r24, 1         ; floor: q -= 1
    sbci r25, 0
    sbci r22, 0
    sbci r23, 0
__divs32_done:
    pop  r9
    pop  r8
    pop  r7
    pop  r6
    pop  r5
    pop  r4
    ret

__mods32:
    push r4
    push r5
    push r6
    push r7
    push r8             ; sign(a)
    push r9             ; sign(b)
    push r10            ; original b (signed): r13:r12:r11:r10
    push r11
    push r12
    push r13
    mov  r8, r23
    mov  r9, r21
    mov  r10, r18
    mov  r11, r19
    mov  r12, r20
    mov  r13, r21
    sbrs r23, 7
    rjmp __mods32_absb
    com  r23            ; |a|
    com  r22
    com  r25
    neg  r24
    sbci r25, 0xFF
    sbci r22, 0xFF
    sbci r23, 0xFF
__mods32_absb:
    sbrs r21, 7
    rjmp __mods32_div
    com  r21            ; |b|
    com  r20
    com  r19
    neg  r18
    sbci r19, 0xFF
    sbci r20, 0xFF
    sbci r21, 0xFF
__mods32_div:
    clr  r4
    clr  r5
    clr  r6
    clr  r7
    ldi  r16, 33
    rcall __div32_core  ; remainder R7:R6:R5:R4
    sbrs r8, 7
    rjmp __mods32_floor
    com  r4             ; truncating remainder takes the sign of a.
    com  r5             ; R4-R7 are low regs (no SBCI), so negate as ~v + 1 using the
    com  r6             ; zero register R1: complement all bytes, then add 1 with carry.
    com  r7
    sec
    adc  r4, r1
    adc  r5, r1
    adc  r6, r1
    adc  r7, r1
__mods32_floor:
    mov  r0, r8
    eor  r0, r9
    sbrs r0, 7
    rjmp __mods32_out   ; signs equal -> trunc remainder == floor
    mov  r0, r4         ; remainder != 0 ?
    or   r0, r5
    or   r0, r6
    or   r0, r7
    breq __mods32_out
    add  r4, r10        ; floor: r += original b
    adc  r5, r11
    adc  r6, r12
    adc  r7, r13
__mods32_out:
    mov  r24, r4        ; remainder -> output registers
    mov  r25, r5
    mov  r22, r6
    mov  r23, r7
    pop  r13
    pop  r12
    pop  r11
    pop  r10
    pop  r9
    pop  r8
    pop  r7
    pop  r6
    pop  r5
    pop  r4
    ret


__bad_interrupt:
	JMP	main

delay_1ms_avr_16mhz:
    PUSH R24
    PUSH R25
    LDI R24, 24
_dly_o16mhz:
    LDI R25, 221
_dly_i16mhz:
    DEC R25
    BRNE _dly_i16mhz
    DEC R24
    BRNE _dly_o16mhz
    POP R25
    POP R24
	RET
pymcu_time__delay_ms_avr:
	MOV	R8, R24
	MOV	R9, R25
	LDI	R24, 0
	LDI	R25, 0
	MOV	R4, R24
	MOV	R5, R25
L_0:
	MOV	R24, R4
	MOV	R25, R5
	MOV	R18, R8
	MOV	R19, R9
	CP	R24, R18
	CPC	R25, R19
	BRSH	L_1
	CALL	delay_1ms_avr_16mhz
	MOV	R24, R4
	MOV	R25, R5
	ADIW	R24, 1
	MOV	R4, R24
	MOV	R5, R25
	JMP	L_0
L_1:
	RET
play_note:
	MOV	R2, R24
	MOV	R3, R25
	MOV	R6, R22
	MOV	R7, R23

	SBI	0x04, 3
	LDI	R24, 0
	STS	0x0070, R24
	LDI	R24, 66
	STS	0x00B0, R24
	MOV	R24, R2
	LDI	R18, 133
	LDI	R19, 30
	CP	R24, R18
	CPC	R25, R19
	BRSH	L_BR_SKIP_1
	JMP	L_13
L_BR_SKIP_1:
	MOV	R24, R2
	MOV	R25, R3
	CLR	R22
	CLR	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	STD	Y+4, R24
	STD	Y+5, R25
	STD	Y+6, R22
	STD	Y+7, R23
	OR	R24, R25
	OR	R24, R22
	OR	R24, R23
	BRNE	L_15
	LDI	R22, 6
	SET
	RET
L_15:
	LDI	R24, 0
	LDI	R25, 36
	LDI	R22, 244
	LDI	R23, 0
	LDD	R18, Y+4
	LDD	R19, Y+5
	LDD	R20, Y+6
	LDD	R21, Y+7
	CALL	__div32
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRSH	L_16
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_14
L_16:
	LDD	R24, Y+8
	LDD	R25, Y+9
	LDD	R22, Y+10
	LDD	R23, Y+11
	LDI	R18, 0
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRLO	L_17
	LDI	R24, 255
	MOV	R16, R24
	JMP	L_14
L_17:
	LDD	R24, Y+8
	DEC	R24
	MOV	R16, R24
L_14:
	MOV	R24, R16
	STS	0x00B3, R24
	LDI	R24, 1
	STS	0x00B1, R24
	JMP	L_12
L_13:
	MOV	R24, R2
	MOV	R25, R3
	LDI	R18, 209
	LDI	R19, 3
	CP	R24, R18
	CPC	R25, R19
	BRSH	L_BR_SKIP_5
	JMP	L_18
L_BR_SKIP_5:
	MOV	R24, R2
	MOV	R25, R3
	CLR	R22
	CLR	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	STD	Y+13, R24
	STD	Y+14, R25
	STD	Y+15, R22
	STD	Y+16, R23
	OR	R24, R25
	OR	R24, R22
	OR	R24, R23
	BRNE	L_20
	LDI	R22, 6
	SET
	RET
L_20:
	LDI	R24, 0
	LDI	R25, 36
	LDI	R22, 244
	LDI	R23, 0
	LDD	R18, Y+13
	LDD	R19, Y+14
	LDD	R20, Y+15
	LDD	R21, Y+16
	CALL	__div32
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRSH	L_21
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_19
L_21:
	LDD	R24, Y+8
	LDD	R25, Y+9
	LDD	R22, Y+10
	LDD	R23, Y+11
	LDI	R18, 0
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRLO	L_22
	LDI	R24, 255
	MOV	R16, R24
	JMP	L_19
L_22:
	LDD	R24, Y+8
	DEC	R24
	MOV	R16, R24
L_19:
	MOV	R24, R16
	STS	0x00B3, R24
	LDI	R24, 2
	STS	0x00B1, R24
	JMP	L_12
L_18:
	MOV	R24, R2
	MOV	R25, R3
	LDI	R18, 233
	LDI	R19, 1
	CP	R24, R18
	CPC	R25, R19
	BRSH	L_BR_SKIP_9
	JMP	L_23
L_BR_SKIP_9:
	MOV	R24, R2
	MOV	R25, R3
	CLR	R22
	CLR	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	STD	Y+18, R24
	STD	Y+19, R25
	STD	Y+20, R22
	STD	Y+21, R23
	OR	R24, R25
	OR	R24, R22
	OR	R24, R23
	BRNE	L_25
	LDI	R22, 6
	SET
	RET
L_25:
	LDI	R24, 0
	LDI	R25, 36
	LDI	R22, 244
	LDI	R23, 0
	LDD	R18, Y+18
	LDD	R19, Y+19
	LDD	R20, Y+20
	LDD	R21, Y+21
	CALL	__div32
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRSH	L_26
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_24
L_26:
	LDD	R24, Y+8
	LDD	R25, Y+9
	LDD	R22, Y+10
	LDD	R23, Y+11
	LDI	R18, 0
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRLO	L_27
	LDI	R24, 255
	MOV	R16, R24
	JMP	L_24
L_27:
	LDD	R24, Y+8
	DEC	R24
	MOV	R16, R24
L_24:
	MOV	R24, R16
	STS	0x00B3, R24
	LDI	R24, 3
	STS	0x00B1, R24
	JMP	L_12
L_23:
	MOV	R24, R2
	MOV	R25, R3
	CPI	R24, 244
	CPC	R25, R1
	BRSH	L_BR_SKIP_13
	JMP	L_28
L_BR_SKIP_13:
	MOV	R24, R2
	MOV	R25, R3
	CLR	R22
	CLR	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	STD	Y+23, R24
	STD	Y+24, R25
	STD	Y+25, R22
	STD	Y+26, R23
	OR	R24, R25
	OR	R24, R22
	OR	R24, R23
	BRNE	L_30
	LDI	R22, 6
	SET
	RET
L_30:
	LDI	R24, 0
	LDI	R25, 36
	LDI	R22, 244
	LDI	R23, 0
	LDD	R18, Y+23
	LDD	R19, Y+24
	LDD	R20, Y+25
	LDD	R21, Y+26
	CALL	__div32
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRSH	L_31
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_29
L_31:
	LDD	R24, Y+8
	LDD	R25, Y+9
	LDD	R22, Y+10
	LDD	R23, Y+11
	LDI	R18, 0
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRLO	L_32
	LDI	R24, 255
	MOV	R16, R24
	JMP	L_29
L_32:
	LDD	R24, Y+8
	DEC	R24
	MOV	R16, R24
L_29:
	MOV	R24, R16
	STS	0x00B3, R24
	LDI	R24, 4
	STS	0x00B1, R24
	JMP	L_12
L_28:
	MOV	R24, R2
	MOV	R25, R3
	CPI	R24, 122
	CPC	R25, R1
	BRSH	L_BR_SKIP_17
	JMP	L_33
L_BR_SKIP_17:
	MOV	R24, R2
	MOV	R25, R3
	CLR	R22
	CLR	R23
	MOV	R22, R25
	MOV	R25, R24
	CLR	R24
	STD	Y+28, R24
	STD	Y+29, R25
	STD	Y+30, R22
	STD	Y+31, R23
	OR	R24, R25
	OR	R24, R22
	OR	R24, R23
	BRNE	L_35
	LDI	R22, 6
	SET
	RET
L_35:
	LDI	R24, 0
	LDI	R25, 36
	LDI	R22, 244
	LDI	R23, 0
	LDD	R18, Y+28
	LDD	R19, Y+29
	LDD	R20, Y+30
	LDD	R21, Y+31
	CALL	__div32
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRSH	L_36
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_34
L_36:
	LDD	R24, Y+8
	LDD	R25, Y+9
	LDD	R22, Y+10
	LDD	R23, Y+11
	LDI	R18, 0
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRLO	L_37
	LDI	R24, 255
	MOV	R16, R24
	JMP	L_34
L_37:
	LDD	R24, Y+8
	DEC	R24
	MOV	R16, R24
L_34:
	MOV	R24, R16
	STS	0x00B3, R24
	LDI	R24, 5
	STS	0x00B1, R24
	JMP	L_12
L_33:
	MOV	R24, R2
	MOV	R25, R3
	CPI	R24, 61
	CPC	R25, R1
	BRSH	L_BR_SKIP_21
	JMP	L_38
L_BR_SKIP_21:
	MOV	R24, R2
	MOV	R25, R3
	CLR	R22
	CLR	R23
	MOV	R22, R25
	MOV	R25, R24
	CLR	R24
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	STD	Y+33, R24
	STD	Y+34, R25
	STD	Y+35, R22
	STD	Y+36, R23
	OR	R24, R25
	OR	R24, R22
	OR	R24, R23
	BRNE	L_40
	LDI	R22, 6
	SET
	RET
L_40:
	LDI	R24, 0
	LDI	R25, 36
	LDI	R22, 244
	LDI	R23, 0
	LDD	R18, Y+33
	LDD	R19, Y+34
	LDD	R20, Y+35
	LDD	R21, Y+36
	CALL	__div32
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRSH	L_41
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_39
L_41:
	LDD	R24, Y+8
	LDD	R25, Y+9
	LDD	R22, Y+10
	LDD	R23, Y+11
	LDI	R18, 0
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRLO	L_42
	LDI	R24, 255
	MOV	R16, R24
	JMP	L_39
L_42:
	LDD	R24, Y+8
	DEC	R24
	MOV	R16, R24
L_39:
	MOV	R24, R16
	STS	0x00B3, R24
	LDI	R24, 6
	STS	0x00B1, R24
	JMP	L_12
L_38:
	MOV	R24, R2
	MOV	R25, R3
	CLR	R22
	CLR	R23
	MOV	R22, R25
	MOV	R25, R24
	CLR	R24
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	LSL	R24
	ROL	R25
	ROL	R22
	ROL	R23
	STD	Y+38, R24
	STD	Y+39, R25
	STD	Y+40, R22
	STD	Y+41, R23
	OR	R24, R25
	OR	R24, R22
	OR	R24, R23
	BRNE	L_44
	LDI	R22, 6
	SET
	RET
L_44:
	LDI	R24, 0
	LDI	R25, 36
	LDI	R22, 244
	LDI	R23, 0
	LDD	R18, Y+38
	LDD	R19, Y+39
	LDD	R20, Y+40
	LDD	R21, Y+41
	CALL	__div32
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRSH	L_45
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_43
L_45:
	LDD	R24, Y+8
	LDD	R25, Y+9
	LDD	R22, Y+10
	LDD	R23, Y+11
	LDI	R18, 0
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
	CP	R24, R18
	CPC	R25, R19
	CPC	R22, R20
	CPC	R23, R21
	BRLO	L_46
	LDI	R24, 255
	MOV	R16, R24
	JMP	L_43
L_46:
	LDD	R24, Y+8
	DEC	R24
	MOV	R16, R24
L_43:
	MOV	R24, R16
	STS	0x00B3, R24
	LDI	R24, 7
	STS	0x00B1, R24
L_12:

	MOV	R24, R6
	MOV	R25, R7
	CALL	pymcu_time__delay_ms_avr

	LDI	R24, 0
	STS	0x00B1, R24
	STS	0x00B0, R24
	CBI	0x05, 3

	LDI	R18, 213
	LDI	R19, 8
	LDI	R20, 2
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	CLT
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

L_51:

	LDI	R24, 6
	LDI	R25, 1
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_28
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_28:

	LDI	R24, 38
	LDI	R25, 1
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_29
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_29:

	LDI	R24, 74
	LDI	R25, 1
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_30
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_30:

	LDI	R24, 93
	LDI	R25, 1
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_31
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_31:

	LDI	R24, 136
	LDI	R25, 1
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_32
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_32:

	LDI	R24, 184
	LDI	R25, 1
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_33
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_33:

	LDI	R24, 238
	LDI	R25, 1
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_34
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_34:

	LDI	R24, 11
	LDI	R25, 2
	LDI	R22, 44
	LDI	R23, 1
	CALL	play_note
	BRTC	L_BR_SKIP_35
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_35:

	LDI	R18, 85
	LDI	R19, 88
	LDI	R20, 20
	LDI	R21, 0
_dly_L1:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L1
	JMP	L_51
; ── Exception runtime ──────────────────────────────────────────────────────
__exn_str_6:
    .byte 69, 58, 69, 120, 99, 101, 112, 116, 105, 111, 110, 54, 13, 10, 0
.balign 2
    .balign 2

__pymcu_unhandled_exn:
    lds   R16, 0xC1
    sbrs  R16, 3
    rjmp  __exn_halt
    ldi   R30, lo8(__exn_str_6)
    ldi   R31, hi8(__exn_str_6)
__exn_print_loop:
    lpm   R16, Z+
    tst   R16
    breq  __exn_halt
__exn_wait_udre:
    lds   R17, 0xC0
    sbrs  R17, 5
    rjmp  __exn_wait_udre
    sts   0xC6, R16
    rjmp  __exn_print_loop
__exn_halt:
    cli
    rjmp  .-2

