; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ main_readings, _stack_base + 0
.equ tmp_94, _stack_base + 23
.equ tmp_98, _stack_base + 27
.equ inline2_adc_read_result, _stack_base + 31
.equ tmp_100, _stack_base + 33
.equ main_average, _stack_base + 35
.equ tmp_104, _stack_base + 37
.equ tmp_14, _stack_base + 43
.equ tmp_15, _stack_base + 44
.equ __pymcu_outline_0_p0, _stack_base + 47
.equ _s610f894f, _stack_base + 39
.equ _s500f6e8c, _stack_base + 42
.equ delay_ms_avr_ms, _stack_base + 39

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt


; --- PyMCU AVR Math Runtime ---
; -----------------------------------------------------------------------------
; PyMCU AVR Math Runtime
; -----------------------------------------------------------------------------
;
; __div16: Unsigned 16-bit Division
;   Input:  R25:R24 (Dividend), R19:R18 (Divisor)
;   Output: R25:R24 (Quotient), R27:R26 (Remainder)
;   Clobbers: R26, R27, R21
;
; __mod16: Unsigned 16-bit Modulo
;   Input:  R25:R24 (Dividend), R19:R18 (Divisor)
;   Output: R25:R24 (Remainder)
;   Clobbers: R26, R27, R21
;
; Restoring long division with the inverted-quotient trick (as in avr-libc's
; __udivmodhi4): each iteration shifts the dividend left, the carry it produces
; becomes the complemented quotient bit, and a single COM at the end fixes up
; all 16 bits. One loop back-edge instead of two, and the loop counter lives in
; the call-clobbered R21 so no push/pop is needed. R21 is free at every div/mod
; call site (operands are staged in R24:R25 / R18:R19), and 16-bit temporaries
; live across a call are spilled, so R16:R17 are likewise untouched here.
; -----------------------------------------------------------------------------

__div16:
    sub r26, r26        ; Remainder Low  = 0 (also clears Carry)
    sub r27, r27        ; Remainder High = 0
    ldi r21, 17         ; Loop counter = 16 + 1
    rjmp __div16_ep     ; Enter at the dividend-shift point

__div16_loop:
    rol r26             ; Shift the dividend's top bit into the remainder
    rol r27
    sub r26, r18        ; Remainder -= Divisor
    sbc r27, r19
    brcc __div16_ep     ; Rem >= Div: keep the subtraction (Carry=0 -> bit 1 after COM)
    add r26, r18        ; Rem < Div: restore the remainder
    adc r27, r19

__div16_ep:
    rol r24             ; Shift dividend left; inverted quotient bit enters from Carry
    rol r25
    dec r21
    brne __div16_loop
    com r24             ; Quotient bits were complemented in the loop -- fix them up
    com r25
    ret

__mod16:
    rcall __div16
    mov r24, r26        ; Move Remainder Low to result
    mov r25, r27        ; Move Remainder High to result
    ret

; -----------------------------------------------------------------------------
; __divs16 / __mods16: SIGNED 16-bit floor division and modulo (Python).
;   Input:  R25:R24 (Dividend a), R19:R18 (Divisor b)   -- both signed
;   Output: __divs16 -> R25:R24 = floor(a/b)
;           __mods16 -> R25:R24 = a - b*floor(a/b)   (sign of b)
;   Net clobber: R25:R24, R27:R26, R21 (same as __div16); R4/R5/R16/R17 saved.
;
; In-place 16-bit negate uses the canonical  com hi / neg lo / sbci hi,0xFF.
; Magnitudes are divided by the unsigned core; the truncating result is signed
; and then floor-corrected once (signs differ & remainder != 0: q-=1; r+=b).
; -----------------------------------------------------------------------------
__divmods16:
    push r4
    push r5
    push r16
    push r17
    mov  r4, r18        ; r5:r4 = original b (signed; used for floor add)
    mov  r5, r19
    mov  r16, r25       ; sign(a) in bit7 of r16
    mov  r17, r19       ; sign(b) in bit7 of r17
    sbrs r25, 7
    rjmp __divmods16_absb
    com  r25            ; |a|
    neg  r24
    sbci r25, 0xFF
__divmods16_absb:
    sbrs r19, 7
    rjmp __divmods16_div
    com  r19            ; |b|
    neg  r18
    sbci r19, 0xFF
__divmods16_div:
    rcall __div16       ; R25:R24 = uq, R27:R26 = ur; R19:R18 preserved
    sbrs r16, 7
    rjmp __divmods16_qsign
    com  r27            ; truncating remainder takes the sign of a
    neg  r26
    sbci r27, 0xFF
__divmods16_qsign:
    eor  r16, r17       ; r16 bit7 = signs differ (quotient negative)
    sbrs r16, 7
    rjmp __divmods16_done   ; signs equal -> trunc == floor
    com  r25            ; negate quotient
    neg  r24
    sbci r25, 0xFF
    mov  r17, r26       ; remainder != 0 ?  (r17 reused as scratch)
    or   r17, r27
    breq __divmods16_done   ; exact -> no correction
    sbiw r24, 1         ; floor: q -= 1
    add  r26, r4        ;        r += original b
    adc  r27, r5
__divmods16_done:
    pop  r17
    pop  r16
    pop  r5
    pop  r4
    ret

__divs16:
    rcall __divmods16
    ret                 ; quotient already in R25:R24

__mods16:
    rcall __divmods16
    mov  r24, r26       ; remainder -> result registers
    mov  r25, r27
    ret


__bad_interrupt:
	JMP	main

_s6977b1d6:
	MOV	R4, R24
	MOV	R5, R25
	LDI	R24, 0
	MOV	R3, R24
	LDI	R24, 48
	MOV	R2, R24
L_26:
	MOV	R24, R4
	MOV	R25, R5
	LDI	R18, 16
	LDI	R19, 39
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_27
	SUBI	R24, 16
	SBCI	R25, 39
	MOV	R4, R24
	MOV	R5, R25
	INC	R2
	MOV	R24, R2
	JMP	L_26
L_27:
	MOV	R24, R2
	CPI	R24, 48
	BRNE	L_29
	MOV	R24, R3
	CPI	R24, 1
	BRNE	L_28
L_29:
	MOV	R24, R2
	CALL	__pymcu_outline_0
	LDI	R24, 1
	MOV	R3, R24
L_28:
	LDI	R24, 48
	MOV	R2, R24
L_33:
	MOV	R24, R4
	MOV	R25, R5
	LDI	R18, 232
	LDI	R19, 3
	CP	R24, R18
	CPC	R25, R19
	BRLO	L_34
	SUBI	R24, 232
	SBCI	R25, 3
	MOV	R4, R24
	MOV	R5, R25
	INC	R2
	MOV	R24, R2
	JMP	L_33
L_34:
	MOV	R24, R2
	CPI	R24, 48
	BRNE	L_36
	MOV	R24, R3
	CPI	R24, 1
	BRNE	L_35
L_36:
	MOV	R24, R2
	CALL	__pymcu_outline_0
	LDI	R24, 1
	MOV	R3, R24
L_35:
	LDI	R24, 48
	MOV	R2, R24
L_40:
	MOV	R24, R4
	MOV	R25, R5
	CPI	R24, 100
	CPC	R25, R1
	BRLO	L_41
	SUBI	R24, 100
	SBCI	R25, 0
	MOV	R4, R24
	MOV	R5, R25
	INC	R2
	MOV	R24, R2
	JMP	L_40
L_41:
	MOV	R24, R2
	CPI	R24, 48
	BRNE	L_43
	MOV	R24, R3
	CPI	R24, 1
	BRNE	L_42
L_43:
	MOV	R24, R2
	CALL	__pymcu_outline_0
	LDI	R24, 1
	MOV	R3, R24
L_42:
	LDI	R24, 48
	MOV	R2, R24
L_47:
	MOV	R24, R4
	MOV	R25, R5
	CPI	R24, 10
	CPC	R25, R1
	BRLO	L_48
	SBIW	R24, 10
	MOV	R4, R24
	MOV	R5, R25
	INC	R2
	MOV	R24, R2
	JMP	L_47
L_48:
	MOV	R24, R2
	CPI	R24, 48
	BRNE	L_50
	MOV	R24, R3
	CPI	R24, 1
	BRNE	L_49
L_50:
	MOV	R24, R2
	CALL	__pymcu_outline_0
	LDI	R24, 1
	MOV	R3, R24
L_49:
	MOV	R24, R4
	CLR	R25
	ADIW	R24, 48
	STD	Y+44, R24
	STD	Y+45, R25
	MOV	R12, R24
L_55:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_55
	MOV	R24, R12
	STS	0x00C6, R24
	RET
_s4e65a6dd:
	STD	Y+39, R24
	STD	Y+40, R25
	LDI	R24, 0
	MOV	R11, R24
	LDD	R30, Y+39
	LDD	R31, Y+40
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+42, R24
L_164:
	LDD	R24, Y+42
	CPI	R24, 0
	BREQ	L_165
	LDD	R24, Y+42
	CALL	__pymcu_outline_0
	INC	R11
	LDD	R30, Y+39
	LDD	R31, Y+40
	MOV	R24, R11
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+42, R24
	JMP	L_164
L_165:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 64
	STS	0x007C, R24
	LDI	R24, 135
	STS	0x007A, R24

	LDI	R24, 0
	LDI	R25, 0
	STD	Y+0, R24
	STD	Y+1, R25
	STD	Y+2, R24
	STD	Y+3, R25
	STD	Y+4, R24
	STD	Y+5, R25
	STD	Y+6, R24
	STD	Y+7, R25
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R24
	STD	Y+11, R25
	STD	Y+12, R24
	STD	Y+13, R25
	STD	Y+14, R24
	STD	Y+15, R25
	STD	Y+16, R24
	STD	Y+17, R25
	STD	Y+18, R24
	STD	Y+19, R25

	MOV	R6, R24

	MOV	R7, R24
	MOV	R8, R25

L_212:

; ArrayLoad variable index via Z
	MOV	R24, R6
	LSL	R24
	LDI	R30, lo8(256)
	LDI	R31, hi8(256)
	ADD	R30, R24
	ADC	R31, R1
	LD	R24, Z
	LDD	R25, Z+1
	MOV	R16, R24
	MOV	R17, R25
	SUB	R7, R16
	SBC	R8, R17

	LDS	R24, 0x007A
	ORI	R24, 64
	STS	0x007A, R24
L_216:
	LDS	R24, 0x007A
	ANDI	R24, 64
	BRNE	L_216
	LDS	R24, 0x0078
	MOV	R14, R24
	LDS	R24, 0x0079
	MOV	R13, R24
	CLR	R25
	CLR	R22
	CLR	R23
	MOV	R25, R24
	CLR	R24
	STD	Y+27, R24
	STD	Y+28, R25
	STD	Y+29, R22
	STD	Y+30, R23
	MOV	R24, R14
	CLR	R25
	LDD	R18, Y+27
	LDD	R19, Y+28
	ADD	R24, R18
	ADC	R25, R19
	STD	Y+31, R24
	STD	Y+32, R25
	MOV	R18, R24
	MOV	R19, R25
; ArrayStore variable index via Z
	MOV	R24, R6
	LSL	R24
	LDI	R30, lo8(256)
	LDI	R31, hi8(256)
	ADD	R30, R24
	ADC	R31, R1
	ST	Z, R18
	STD	Z+1, R19

	LD	R24, Z
	LDD	R25, Z+1
	MOV	R16, R24
	MOV	R17, R25
	ADD	R7, R16
	ADC	R8, R17

	INC	R6

	MOV	R24, R6
	CPI	R24, 10
	BRLO	L_218

	LDI	R24, 0
	MOV	R6, R24
L_218:

	MOV	R24, R7
	MOV	R25, R8
	LDI	R18, 10
	LDI	R19, 0
	CALL	__div16
	STD	Y+35, R24
	STD	Y+36, R25

	CALL	_s6977b1d6
	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd

	LDI	R18, 106
	LDI	R19, 10
	LDI	R20, 0
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	JMP	L_212
__pymcu_outline_0:
	STD	Y+47, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	LDD	R24, Y+47
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 10, 0
.balign 2
	.balign 2
