; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 1
.equ delay_us_avr_us, _stack_base + 1
.equ delay_ms_avr_ms, _stack_base + 1

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+1, R24
	STD	Y+2, R25
	LDI	R24, 0
	MOV	R9, R24
	LDD	R30, Y+1
	LDD	R31, Y+2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R10, R24
L_164:
	MOV	R24, R10
	CPI	R24, 0
	BREQ	L_165
L_167:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_167
	MOV	R24, R10
	STS	0x00C6, R24
	INC	R9
	LDD	R30, Y+1
	LDD	R31, Y+2
	MOV	R24, R9
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R10, R24
	JMP	L_164
L_165:
	RET
ws2812_d:
	MOV	R4, R24
	MOV	R14, R22
	LDI	R24, 8
	MOV	R5, R24
	MOV	R24, R14
	MOV	R2, R24
L_216:
	MOV	R24, R5
	CPI	R24, 1
	BRSH	L_BR_SKIP_2
	JMP	L_217
L_BR_SKIP_2:
	MOV	R24, R4
	CPI	R24, 2
	BRNE	L_219
	SBI	0x0B, 2
	MOV	R24, R2
	CPI	R24, 128
	BRSH	L_220
	CBI	0x0B, 2
L_220:
	CBI	0x0B, 2
	JMP	L_218
L_219:
	MOV	R24, R4
	CPI	R24, 3
	BRNE	L_222
	SBI	0x0B, 3
	MOV	R24, R2
	CPI	R24, 128
	BRSH	L_223
	CBI	0x0B, 3
L_223:
	CBI	0x0B, 3
	JMP	L_218
L_222:
	MOV	R24, R4
	CPI	R24, 4
	BRNE	L_225
	SBI	0x0B, 4
	MOV	R24, R2
	CPI	R24, 128
	BRSH	L_226
	CBI	0x0B, 4
L_226:
	CBI	0x0B, 4
	JMP	L_218
L_225:
	MOV	R24, R4
	CPI	R24, 5
	BRNE	L_228
	SBI	0x0B, 5
	MOV	R24, R2
	CPI	R24, 128
	BRSH	L_229
	CBI	0x0B, 5
L_229:
	CBI	0x0B, 5
	JMP	L_218
L_228:
	MOV	R24, R4
	CPI	R24, 6
	BRNE	L_231
	SBI	0x0B, 6
	MOV	R24, R2
	CPI	R24, 128
	BRSH	L_232
	CBI	0x0B, 6
L_232:
	CBI	0x0B, 6
	JMP	L_218
L_231:
	MOV	R24, R4
	CPI	R24, 7
	BRNE	L_234
	SBI	0x0B, 7
	MOV	R24, R2
	CPI	R24, 128
	BRSH	L_235
	CBI	0x0B, 7
L_235:
	CBI	0x0B, 7
	JMP	L_218
L_234:
L_218:
	MOV	R24, R2
	LSL	R24
	MOV	R2, R24
	DEC	R5
	JMP	L_216
L_217:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	SBI	0x0A, 6
	CBI	0x0B, 6

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_263:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_263
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 0
	MOV	R3, R24

L_265:

CLI

	MOV	R24, R3
	CPI	R24, 0
	BRNE	L_269

	LDI	R24, 0
	LDI	R22, 255
	LDI	R20, 0
	CALL	__pymcu_outline_1

	CALL	__pymcu_outline_0
	JMP	L_268
L_269:
	MOV	R24, R3
	CPI	R24, 1
	BRNE	L_337

	LDI	R24, 255
	LDI	R22, 0
	LDI	R20, 0
	CALL	__pymcu_outline_1

	CALL	__pymcu_outline_0
	JMP	L_268
L_337:
	MOV	R24, R3
	CPI	R24, 2
	BRNE	L_268

	LDI	R24, 0
	LDI	R22, 0
	LDI	R20, 255
	CALL	__pymcu_outline_1

	CALL	__pymcu_outline_0
L_268:

SEI

L_475:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_475
	MOV	R24, R3
	STS	0x00C6, R24

L_479:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_479
	LDI	R24, 10
	STS	0x00C6, R24

	INC	R3
	MOV	R24, R3

	CPI	R24, 3
	BRLO	L_481

	LDI	R24, 0
	MOV	R3, R24
L_481:

	LDI	R18, 85
	LDI	R19, 88
	LDI	R20, 20
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	JMP	L_265
__pymcu_outline_0:
	CBI	0x0B, 6
	LDI	R18, 146
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
_dly_L1:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L1
	RET
__pymcu_outline_1:
	MOV	R11, R24
	MOV	R12, R22
	MOV	R13, R20
	LDI	R24, 6
	MOV	R22, R11
	CALL	ws2812_d
	LDI	R24, 6
	MOV	R22, R12
	CALL	ws2812_d
	LDI	R24, 6
	MOV	R22, R13
	CALL	ws2812_d
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 78, 69, 79, 0
.balign 2
	.balign 2
