; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 4

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+4, R24
	STD	Y+5, R25
	LDI	R24, 0
	MOV	R2, R24
	LDD	R30, Y+4
	LDD	R31, Y+5
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R7, R24
L_154:
	MOV	R24, R7
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R7
	STS	0x00C6, R24
	INC	R2
	LDD	R30, Y+4
	LDD	R31, Y+5
	MOV	R24, R2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R7, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24


	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0

L_197:
	SBIS	0x1F, 1
	JMP	L_198
	JMP	L_197
L_198:
	LDI	R24, 0
	OUT	0x21, R24
	OUT	0x22, R24
	LDI	R24, 161
	OUT	0x20, R24
ldi r16, 0x04
out 0x1f, r16
sbi 0x1f, 1

L_201:
	SBIS	0x1F, 1
	JMP	L_202
	JMP	L_201
L_202:
	LDI	R24, 1
	OUT	0x21, R24
	LDI	R24, 0
	OUT	0x22, R24
	LDI	R24, 178
	OUT	0x20, R24
ldi r16, 0x04
out 0x1f, r16
sbi 0x1f, 1

L_205:
	SBIS	0x1F, 1
	JMP	L_206
	JMP	L_205
L_206:
	LDI	R24, 2
	OUT	0x21, R24
	LDI	R24, 0
	OUT	0x22, R24
	LDI	R24, 195
	OUT	0x20, R24
ldi r16, 0x04
out 0x1f, r16
sbi 0x1f, 1

L_209:
	SBIS	0x1F, 1
	JMP	L_210
	JMP	L_209
L_210:
	LDI	R24, 3
	OUT	0x21, R24
	LDI	R24, 0
	OUT	0x22, R24
	LDI	R24, 212
	OUT	0x20, R24
ldi r16, 0x04
out 0x1f, r16
sbi 0x1f, 1

	LDI	R24, 0
	CALL	__pymcu_outline_1
	IN	R24, 0x20
	MOV	R3, R24

	LDI	R24, 1
	CALL	__pymcu_outline_1
	IN	R24, 0x20
	MOV	R4, R24

	LDI	R24, 2
	CALL	__pymcu_outline_1
	IN	R24, 0x20
	MOV	R5, R24

	LDI	R24, 3
	CALL	__pymcu_outline_1
	IN	R24, 0x20
	MOV	R6, R24

	MOV	R24, R3
	CPI	R24, 161
	BRNE	L_228
	MOV	R24, R4
	CPI	R24, 178
	BRNE	L_228
	MOV	R24, R5
	CPI	R24, 195
	BRNE	L_228
	MOV	R24, R6
	CPI	R24, 212
	BRNE	L_228

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_227
L_228:

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
L_227:

L_241:
	JMP	L_241
__pymcu_outline_0:
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	LDI	R24, 10
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
	MOV	R8, R24
__pymcu_outline_1.L0:
	SBIS	0x1F, 1
	JMP	__pymcu_outline_1.L1
	JMP	__pymcu_outline_1.L0
__pymcu_outline_1.L1:
	MOV	R24, R8
	OUT	0x21, R24
	LDI	R24, 0
	OUT	0x22, R24
	SBI	0x1F, 0
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 69, 69, 80, 82, 79, 77, 32, 84, 69, 83, 84, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 69, 69, 80, 82, 79, 77, 32, 79, 75, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 69, 69, 80, 82, 79, 77, 32, 70, 65, 73, 76, 0
.balign 2
	.balign 2
