; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 6
	LDI	R24, 0
	OUT	0x27, R24
	LDI	R24, 131
	OUT	0x24, R24
	LDI	R24, 3
	OUT	0x25, R24

	OUT	0x25, R24

	LDI	R24, 0
	MOV	R2, R24

	LDI	R24, 1
	MOV	R3, R24

L_40:

	MOV	R24, R2
	OUT	0x27, R24

	LDI	R18, 21
	LDI	R19, 52
	LDI	R20, 0
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	MOV	R24, R3
	CPI	R24, 1
	BRNE	L_45

	MOV	R24, R2
	CPI	R24, 255
	BRNE	L_47

	LDI	R24, 0
	MOV	R3, R24
	JMP	L_46
L_47:

	INC	R2
	MOV	R24, R2
L_46:
	JMP	L_44
L_45:

	MOV	R24, R2
	CPI	R24, 0
	BRNE	L_50

	LDI	R24, 1
	MOV	R3, R24
	JMP	L_49
L_50:

	DEC	R2
	MOV	R24, R2
L_49:
L_44:
	JMP	L_40
