; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 5

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 0
	OUT	0x24, R24
	LDI	R24, 4
	OUT	0x25, R24

	LDI	R24, 0
	OUT	0x26, R24

	LDI	R25, 0
	MOV	R2, R24
	MOV	R3, R25

L_228:

	SBIS	0x15, 0
	JMP	L_230

	SBI	0x15, 0

	MOV	R24, R2
	MOV	R25, R3
	ADIW	R24, 1
	MOV	R2, R24
	MOV	R3, R25

	CPI	R24, 244
	CPC	R25, R1
	BRNE	L_231

	LDI	R24, 0
	LDI	R25, 0
	MOV	R2, R24
	MOV	R3, R25

	SBI	0x03, 5

L_235:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_235
	LDI	R24, 84
	STS	0x00C6, R24

L_239:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_239
	LDI	R24, 10
	STS	0x00C6, R24
L_231:
L_230:
	JMP	L_228
