; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_95, _stack_base + 2
.equ tmp_98, _stack_base + 3
.equ tmp_100, _stack_base + 5
.equ _s610f894f, _stack_base + 7

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4d542624:

	CBI	0x05, 2
	RET
_s5c48f0f7:

	SBI	0x05, 2
	RET
_sb2da76ff:
	MOV	R10, R24

	OUT	0x2E, R24

L_10:
	IN	R24, 0x2D
	ANDI	R24, 128
	BREQ	L_10

	IN	R24, 0x2E
	MOV	R8, R24

	RET
_s4e65a6dd:
	STD	Y+7, R24
	STD	Y+8, R25
	LDI	R24, 0
	MOV	R6, R24
	LDD	R30, Y+7
	LDD	R31, Y+8
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R9, R24
L_166:
	MOV	R24, R9
	CPI	R24, 0
	BREQ	L_167
L_169:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_169
	MOV	R24, R9
	STS	0x00C6, R24
	INC	R6
	LDD	R30, Y+7
	LDD	R31, Y+8
	MOV	R24, R6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R9, R24
	JMP	L_166
L_167:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)




	SBI	0x04, 3
	SBI	0x04, 5
	SBI	0x04, 2
	SBI	0x05, 2
	LDI	R24, 80
	OUT	0x2C, R24

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_210:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_210
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 1
	MOV	R2, R24

	LDI	R24, 0
	MOV	R3, R24

L_212:

	CALL	_s4d542624

	MOV	R24, R2
	CALL	_sb2da76ff
	CALL	_s5c48f0f7

L_226:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_226
	MOV	R24, R2
	STS	0x00C6, R24

	LDI	R18, 0
	LDI	R19, 226
	LDI	R20, 4
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0

	MOV	R24, R2
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 1
	MOV	R7, R24

	MOV	R24, R2
	CLR	R25
	LSL	R24
	ROL	R25
	MOV	R18, R7
	CLR	R19
	OR	R24, R18
	OR	R25, R19
	MOV	R2, R24

	LDS	R24, 0x00C0
	ANDI	R24, 128
	BREQ	L_234

L_237:
	LDS	R24, 0x00C0
	ANDI	R24, 128
	BREQ	L_237

	INC	R3
	MOV	R24, R3

	CPI	R24, 3
	BRNE	L_239

	LDI	R24, 0
	MOV	R3, R24
L_239:

	LDI	R24, 1
	MOV	R2, R24

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
L_246:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_246
	LDI	R24, 10
	STS	0x00C6, R24
L_234:
	JMP	L_212

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 83, 80, 73, 32, 55, 52, 72, 67, 53, 57, 53, 32, 68, 69, 77, 79, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 77, 79, 68, 69, 58, 32, 82, 85, 78, 78, 73, 78, 71, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 77, 79, 68, 69, 58, 32, 67, 72, 65, 83, 69, 82, 0
.balign 2
	.balign 2
__flash___cstr_3:
	.byte 77, 79, 68, 69, 58, 32, 67, 79, 85, 78, 84, 69, 82, 0
.balign 2
	.balign 2
