; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_98, _stack_base + 0
.equ tmp_101, _stack_base + 2
.equ tmp_105, _stack_base + 6
.equ tmp_106, _stack_base + 7
.equ tmp_108, _stack_base + 9
.equ tmp_111, _stack_base + 10
.equ tmp_114, _stack_base + 11
.equ tmp_116, _stack_base + 12
.equ tmp_122, _stack_base + 13
.equ tmp_125, _stack_base + 16
.equ tmp_127, _stack_base + 19
.equ tmp_128, _stack_base + 21
.equ tmp_130, _stack_base + 25
.equ tmp_132, _stack_base + 27
.equ tmp_133, _stack_base + 29
.equ _s610f894f, _stack_base + 33
.equ __pymcu_outline_2_v1, _stack_base + 33

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+33, R24
	STD	Y+34, R25
	LDI	R24, 0
	MOV	R10, R24
	LDD	R30, Y+33
	LDD	R31, Y+34
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R11, R24
L_164:
	MOV	R24, R11
	CPI	R24, 0
	BREQ	L_165
	CALL	__pymcu_outline_0
	INC	R10
	LDD	R30, Y+33
	LDD	R31, Y+34
	MOV	R24, R10
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R11, R24
	JMP	L_164
L_165:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	CBI	0x07, 0

	CBI	0x07, 1

	SBI	0x07, 2

	CBI	0x07, 3

	CBI	0x08, 2
	SBI	0x08, 3

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_1

	CALL	__pymcu_outline_2
	MOV	R9, R24

L_307:
	MOV	R24, R9
	CPI	R24, 0
	BRNE	L_308

	CALL	__pymcu_outline_2
	MOV	R9, R24
	JMP	L_307
L_308:

	LDI	R24, 171
	MOV	R6, R24
	LDI	R24, 0
	MOV	R3, R24
	MOV	R5, R24
L_318:
	MOV	R24, R5
	CPI	R24, 8
	BRSH	L_319
	MOV	R24, R6
	ANDI	R24, 128
	TST	R24
	BREQ	L_321
	SBI	0x08, 2
	JMP	L_320
L_321:
	CBI	0x08, 2
L_320:
	SBIS	0x06, 0
	JMP	L_BIT_FALSE_4
	LDI	R24, 1
	JMP	L_BIT_DONE_5
L_BIT_FALSE_4:
	LDI	R24, 0
L_BIT_DONE_5:
	MOV	R4, R24
L_327:
	MOV	R24, R4
	CPI	R24, 0
	BRNE	L_328
	SBIS	0x06, 0
	JMP	L_BIT_FALSE_7
	LDI	R24, 1
	JMP	L_BIT_DONE_8
L_BIT_FALSE_7:
	LDI	R24, 0
L_BIT_DONE_8:
	MOV	R4, R24
	JMP	L_327
L_328:
	MOV	R24, R3
	LSL	R24
	MOV	R3, R24
	SBIS	0x06, 1
	JMP	L_BIT_FALSE_9
	LDI	R24, 1
	JMP	L_BIT_DONE_10
L_BIT_FALSE_9:
	LDI	R24, 0
L_BIT_DONE_10:
	TST	R24
	BREQ	L_332
	MOV	R24, R3
	ORI	R24, 1
	MOV	R3, R24
L_332:
	SBIS	0x06, 0
	JMP	L_BIT_FALSE_12
	LDI	R24, 1
	JMP	L_BIT_DONE_13
L_BIT_FALSE_12:
	LDI	R24, 0
L_BIT_DONE_13:
	MOV	R4, R24
L_339:
	MOV	R24, R4
	CPI	R24, 1
	BRNE	L_340
	SBIS	0x06, 0
	JMP	L_BIT_FALSE_15
	LDI	R24, 1
	JMP	L_BIT_DONE_16
L_BIT_FALSE_15:
	LDI	R24, 0
L_BIT_DONE_16:
	MOV	R4, R24
	JMP	L_339
L_340:
	MOV	R24, R6
	LSL	R24
	MOV	R6, R24
	INC	R5
	JMP	L_318
L_319:

	LDI	R24, 82
	CALL	__pymcu_outline_1

	LDI	R24, 58
	CALL	__pymcu_outline_1

	MOV	R24, R3
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 15
	MOV	R7, R24
	MOV	R24, R3
	ANDI	R24, 15
	MOV	R8, R24
	MOV	R24, R7
	CPI	R24, 10
	BRSH	L_354
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_353
L_354:
	MOV	R24, R7
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+21, R24
	STD	Y+22, R25
	STD	Y+23, R22
	STD	Y+24, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_353:
	MOV	R24, R8
	CPI	R24, 10
	BRSH	L_364
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_363
L_364:
	MOV	R24, R8
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+29, R24
	STD	Y+30, R25
	STD	Y+31, R22
	STD	Y+32, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_363:

	LDI	R24, 10
	CALL	__pymcu_outline_1

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_1

L_383:
	JMP	L_383
__pymcu_outline_0:
	MOV	R12, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R12
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
	MOV	R13, R24
__pymcu_outline_1.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_1.L0
	MOV	R24, R13
	STS	0x00C6, R24
	RET
__pymcu_outline_2:
	SBIC	0x06, 3
	JMP	__pymcu_outline_2.L0
	LDI	R24, 1
	MOV	R16, R24
	JMP	__pymcu_outline_2.L1
__pymcu_outline_2.L0:
	LDI	R24, 0
	MOV	R16, R24
__pymcu_outline_2.L1:
	MOV	R24, R16
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 83, 83, 80, 73, 80, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 79, 75, 0
.balign 2
	.balign 2
