; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_95, _stack_base + 3
.equ tmp_97, _stack_base + 5
.equ tmp_98, _stack_base + 7
.equ tmp_100, _stack_base + 10

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	CBI	0x0A, 2
	SBI	0x0B, 2

	SBI	0x04, 5

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 0
	LDI	R25, 0
	MOV	R2, R24
	MOV	R3, R25

	LDI	R24, 1
	MOV	R8, R24

L_243:

	SBIS	0x09, 2
	JMP	L_BIT_FALSE_0
	LDI	R24, 1
	JMP	L_BIT_DONE_1
L_BIT_FALSE_0:
	LDI	R24, 0
L_BIT_DONE_1:
	MOV	R7, R24

	CPI	R24, 0
	BRNE	L_248
	MOV	R24, R8
	CPI	R24, 1
	BRNE	L_248

	MOV	R24, R2
	MOV	R25, R3
	ADIW	R24, 1
	MOV	R2, R24
	MOV	R3, R25

	SBI	0x03, 5

	MOV	R24, R25
	CLR	R25
	LDI	R18, 255
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	STD	Y+7, R24
	STD	Y+8, R25
	MOV	R4, R24
L_252:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_252
	MOV	R24, R4
	STS	0x00C6, R24

	MOV	R24, R2
	MOV	R25, R3
	LDI	R18, 255
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	MOV	R4, R24
L_256:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_256
	MOV	R24, R4
	STS	0x00C6, R24

	MOV	R24, R2
	MOV	R25, R3
	LDI	R18, 232
	LDI	R19, 3
	CP	R24, R18
	CPC	R25, R19
	BRNE	L_258

	LDI	R24, 0
	LDI	R25, 0
	MOV	R2, R24
	MOV	R3, R25

L_261:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_261
	LDI	R24, 82
	STS	0x00C6, R24
L_258:
L_248:

	MOV	R24, R7
	MOV	R8, R24

	LDI	R18, 42
	LDI	R19, 104
	LDI	R20, 0
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	JMP	L_243
