; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_110, _stack_base + 2
.equ _s610f894f, _stack_base + 5

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+5, R24
	STD	Y+6, R25
	LDI	R24, 0
	MOV	R6, R24
	LDD	R30, Y+5
	LDD	R31, Y+6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
L_164:
	MOV	R24, R8
	CPI	R24, 0
	BREQ	L_165
L_167:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_167
	MOV	R24, R8
	STS	0x00C6, R24
	INC	R6
	LDD	R30, Y+5
	LDD	R31, Y+6
	MOV	R24, R6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
	JMP	L_164
L_165:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 5

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0

	LDI	R24, 0
	MOV	R3, R24

L_232:

L_236:
	LDS	R24, 0x00C0
	ANDI	R24, 128
	BREQ	L_236
	LDS	R24, 0x00C6
	MOV	R2, R24
	CPI	R24, 66
	BRNE	L_239

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0



	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	SBI	0x03, 5

	CALL	__dly_c266666


	LDI	R24, 0
	MOV	R3, R24

	CBI	0x05, 5
	JMP	L_238
L_239:
	MOV	R24, R2
	CPI	R24, 72
	BRNE	L_251

	SBI	0x05, 5

	LDI	R24, 1
	MOV	R3, R24

	LDI	R24, lo8(__flash___cstr_3)
	LDI	R25, hi8(__flash___cstr_3)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0
	JMP	L_238
L_251:
	MOV	R24, R2
	CPI	R24, 76
	BRNE	L_259

	CBI	0x05, 5

	LDI	R24, 0
	MOV	R3, R24

	LDI	R24, lo8(__flash___cstr_4)
	LDI	R25, hi8(__flash___cstr_4)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0
	JMP	L_238
L_259:
	MOV	R24, R2
	CPI	R24, 84
	BRNE	L_267

	SBI	0x03, 5

	MOV	R24, R3
	CPI	R24, 1
	BRNE	L_270

	LDI	R24, 0
	MOV	R3, R24

	LDI	R24, lo8(__flash___cstr_4)
	LDI	R25, hi8(__flash___cstr_4)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0
	JMP	L_269
L_270:

	LDI	R24, 1
	MOV	R3, R24

	LDI	R24, lo8(__flash___cstr_3)
	LDI	R25, hi8(__flash___cstr_3)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0
L_269:
	JMP	L_238
L_267:
	MOV	R24, R2
	CPI	R24, 83
	BRNE	L_283

	LDI	R24, lo8(__flash___cstr_5)
	LDI	R25, hi8(__flash___cstr_5)
	CALL	_s4e65a6dd

	MOV	R24, R3
	CLR	R25
	ADIW	R24, 48
	MOV	R7, R24
L_287:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_287
	MOV	R24, R7
	STS	0x00C6, R24

	LDI	R24, 10
	CALL	__pymcu_outline_0
	JMP	L_238
L_283:
	MOV	R24, R2
	CPI	R24, 63
	BRNE	L_293

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0
	JMP	L_238
L_293:

	LDI	R24, 63
	CALL	__pymcu_outline_0

L_307:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_307
	MOV	R24, R2
	STS	0x00C6, R24

	LDI	R24, 10
	CALL	__pymcu_outline_0
L_238:
	JMP	L_232
__pymcu_outline_0:
	MOV	R9, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R9
	STS	0x00C6, R24
	RET

__dly_c266666:
	LDI	R18, 169
	LDI	R19, 17
	LDI	R20, 4
	LDI	R21, 0
_dly_S266666:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_S266666
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 85, 65, 82, 84, 32, 67, 77, 68, 32, 82, 69, 65, 68, 89, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 66, 61, 66, 108, 105, 110, 107, 32, 72, 61, 72, 105, 103, 104, 32, 76, 61, 76, 111, 119, 32, 84, 61, 84, 111, 103, 103, 108, 101, 32, 83, 61, 83, 116, 97, 116, 117, 115, 32, 63, 61, 72, 101, 108, 112, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 66, 76, 73, 78, 75, 32, 120, 53, 0
.balign 2
	.balign 2
__flash___cstr_3:
	.byte 76, 69, 68, 32, 79, 78, 0
.balign 2
	.balign 2
__flash___cstr_4:
	.byte 76, 69, 68, 32, 79, 70, 70, 0
.balign 2
	.balign 2
__flash___cstr_5:
	.byte 76, 69, 68, 61, 0
.balign 2
	.balign 2
