; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_101, _stack_base + 3
.equ tmp_103, _stack_base + 5

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 0

	SBI	0x04, 1

	SBI	0x04, 2

	SBI	0x04, 3

	SBI	0x04, 4

	SBI	0x04, 5

	CBI	0x0A, 2
	SBI	0x0B, 2

	CBI	0x0A, 3
	SBI	0x0B, 3

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 0
	MOV	R2, R24

	LDI	R24, 1
	MOV	R7, R24

	MOV	R8, R24

L_376:

	SBIS	0x09, 2
	JMP	L_BIT_FALSE_0
	LDI	R24, 1
	JMP	L_BIT_DONE_1
L_BIT_FALSE_0:
	LDI	R24, 0
L_BIT_DONE_1:
	MOV	R5, R24

	SBIS	0x09, 3
	JMP	L_BIT_FALSE_2
	LDI	R24, 1
	JMP	L_BIT_DONE_3
L_BIT_FALSE_2:
	LDI	R24, 0
L_BIT_DONE_3:
	MOV	R6, R24

	MOV	R24, R5
	CPI	R24, 0
	BRNE	L_384
	MOV	R24, R7
	CPI	R24, 1
	BRNE	L_384

	INC	R2
	MOV	R24, R2

	CPI	R24, 6
	BRNE	L_385

	LDI	R24, 0
	MOV	R2, R24
L_385:
L_384:

	MOV	R24, R6
	CPI	R24, 0
	BRNE	L_386
	MOV	R24, R8
	CPI	R24, 1
	BRNE	L_386

	LDI	R24, 0
	MOV	R2, R24
L_386:

	MOV	R7, R5

	MOV	R8, R6

	CBI	0x05, 0

	CBI	0x05, 1

	CBI	0x05, 2

	CBI	0x05, 3

	CBI	0x05, 4

	CBI	0x05, 5
	MOV	R24, R2
	CPI	R24, 0
	BRNE	L_394

	SBI	0x05, 0
	JMP	L_393
L_394:
	MOV	R24, R2
	CPI	R24, 1
	BRNE	L_396

	SBI	0x05, 1
	JMP	L_393
L_396:
	MOV	R24, R2
	CPI	R24, 2
	BRNE	L_398

	SBI	0x05, 2
	JMP	L_393
L_398:
	MOV	R24, R2
	CPI	R24, 3
	BRNE	L_400

	SBI	0x05, 3
	JMP	L_393
L_400:
	MOV	R24, R2
	CPI	R24, 4
	BRNE	L_402

	SBI	0x05, 4
	JMP	L_393
L_402:
	MOV	R24, R2
	CPI	R24, 5
	BRNE	L_404

	SBI	0x05, 5
	JMP	L_393
L_404:
L_393:

L_408:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_408
	MOV	R24, R2
	STS	0x00C6, R24

	LDI	R18, 85
	LDI	R19, 208
	LDI	R20, 0
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	JMP	L_376
