; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 5
.equ __pymcu_outline_4_v1, _stack_base + 6
.equ __pymcu_outline_4_v2, _stack_base + 7
.equ __pymcu_outline_4_v3, _stack_base + 8
.equ __pymcu_outline_4_v4, _stack_base + 9

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+5, R24
	STD	Y+6, R25
	LDI	R24, 0
	MOV	R9, R24
	LDD	R30, Y+5
	LDD	R31, Y+6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R12, R24
L_154:
	MOV	R24, R12
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R12
	STS	0x00C6, R24
	INC	R9
	LDD	R30, Y+5
	LDD	R31, Y+6
	MOV	R24, R9
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R12, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24


	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_203:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_203
	LDI	R24, 10
	STS	0x00C6, R24

	SBI	0x0A, 4
	SBI	0x0A, 5
	SBI	0x0A, 6
	SBI	0x0A, 7
	SBI	0x04, 0
	SBI	0x04, 1
	CBI	0x0B, 4
	CBI	0x0B, 5
	CBI	0x0B, 6
	CBI	0x0B, 7
	CBI	0x05, 0
	CBI	0x05, 1
	LDI	R18, 213
	LDI	R19, 8
	LDI	R20, 2
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	CBI	0x0B, 4
	CALL	__pymcu_outline_0
	LDI	R18, 21
	LDI	R19, 52
	LDI	R20, 0
	LDI	R21, 0
_dly_L1:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L1
	CALL	__pymcu_outline_0
	CALL	__dly_c293
	CALL	__pymcu_outline_0
	CALL	__dly_c293
	CALL	__pymcu_outline_0
	CALL	__dly_c293
	CBI	0x0B, 4
	CALL	__pymcu_outline_1
	CBI	0x0B, 6
	CBI	0x0B, 7
	CBI	0x05, 0
	SBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	CALL	__dly_c106
	CBI	0x0B, 4
	CALL	__pymcu_outline_0
	CBI	0x0B, 6
	CBI	0x0B, 7
	SBI	0x05, 0
	SBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	CALL	__dly_c106
	CALL	__pymcu_outline_3
	CALL	__dly_c5333
	CBI	0x0B, 4
	LDI	R24, 0
	MOV	R3, R24
	CALL	__pymcu_outline_0
	LDI	R24, 6
	MOV	R2, R24
	CBI	0x0B, 6
	SBI	0x0B, 7
	SBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	CALL	__dly_c106

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
L_3026:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_3026
	LDI	R24, 10
	STS	0x00C6, R24

	CALL	__pymcu_outline_3
	CALL	__dly_c5333

	CBI	0x0B, 4
	LDI	R24, 0
	MOV	R3, R24
	CALL	__pymcu_outline_0
	LDI	R24, 2
	MOV	R2, R24
	CALL	__pymcu_outline_1
	CALL	__dly_c5333

	LDI	R24, 0
	MOV	R8, R24
L_4010:
	MOV	R24, R8
	CPI	R24, 11
	BRSH	L_4012
	LDI	R30, lo8(__flash___cstr_2)
	LDI	R31, hi8(__flash___cstr_2)
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R10, R24
	SBI	0x0B, 4
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	MOV	R3, R24
	CALL	__pymcu_outline_4
	MOV	R24, R10
	ANDI	R24, 15
	MOV	R2, R24
	CALL	__pymcu_outline_4
	CALL	__dly_c106
	INC	R8
	MOV	R24, R8
	JMP	L_4010
L_4012:

	LDI	R24, 192
	MOV	R11, R24
	CBI	0x0B, 4
	LDI	R24, 12
	MOV	R3, R24
	CBI	0x0B, 6
	CBI	0x0B, 7
	SBI	0x05, 0
	SBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	MOV	R24, R11
	ANDI	R24, 15
	MOV	R2, R24
	CALL	__pymcu_outline_4
	CALL	__dly_c106

	SBI	0x0B, 4
	CALL	__pymcu_outline_5
	CALL	__pymcu_outline_0
	CALL	__dly_c106
	SBI	0x0B, 4
	SBI	0x0B, 6
	SBI	0x0B, 7
	SBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	SBI	0x0B, 6
	CBI	0x0B, 7
	CBI	0x05, 0
	SBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	CALL	__dly_c106
	SBI	0x0B, 4
	CALL	__pymcu_outline_6
	SBI	0x0B, 6
	CBI	0x0B, 7
	SBI	0x05, 0
	SBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	CALL	__dly_c106
	SBI	0x0B, 4
	CALL	__pymcu_outline_6
	SBI	0x0B, 6
	SBI	0x0B, 7
	CBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	CALL	__dly_c106
	SBI	0x0B, 4
	LDI	R24, 5
	MOV	R3, R24
	CALL	__pymcu_outline_5
	LDI	R24, 5
	MOV	R2, R24
	CALL	__pymcu_outline_5
	CALL	__dly_c106

L_7435:
	JMP	L_7435
__pymcu_outline_0:
	CBI	0x0B, 6
	CBI	0x0B, 7
	CBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	RET
__pymcu_outline_1:
	CBI	0x0B, 6
	SBI	0x0B, 7
	CBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	RET
__pymcu_outline_2:
	SBI	0x0B, 6
	CBI	0x0B, 7
	CBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	RET
__pymcu_outline_3:
	CBI	0x0B, 4
	CALL	__pymcu_outline_0
	CALL	__pymcu_outline_2
	RET
__pymcu_outline_4:
	MOV	R4, R24
	ANDI	R24, 1
	TST	R24
	BREQ	__pymcu_outline_4.L0
	SBI	0x0B, 6
	JMP	__pymcu_outline_4.L1
__pymcu_outline_4.L0:
	CBI	0x0B, 6
__pymcu_outline_4.L1:
	MOV	R24, R4
	ANDI	R24, 2
	TST	R24
	BREQ	__pymcu_outline_4.L2
	SBI	0x0B, 7
	JMP	__pymcu_outline_4.L3
__pymcu_outline_4.L2:
	CBI	0x0B, 7
__pymcu_outline_4.L3:
	MOV	R24, R4
	ANDI	R24, 4
	TST	R24
	BREQ	__pymcu_outline_4.L4
	SBI	0x05, 0
	JMP	__pymcu_outline_4.L5
__pymcu_outline_4.L4:
	CBI	0x05, 0
__pymcu_outline_4.L5:
	MOV	R24, R4
	ANDI	R24, 8
	TST	R24
	BREQ	__pymcu_outline_4.L6
	SBI	0x05, 1
	JMP	__pymcu_outline_4.L7
__pymcu_outline_4.L6:
	CBI	0x05, 1
__pymcu_outline_4.L7:
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	RET
__pymcu_outline_5:
	SBI	0x0B, 6
	CBI	0x0B, 7
	SBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	RET
__pymcu_outline_6:
	CBI	0x0B, 6
	CBI	0x0B, 7
	SBI	0x05, 0
	CBI	0x05, 1
	SBI	0x0B, 5
	CALL	__dly_c2
	CBI	0x0B, 5
	CALL	__dly_c133
	RET

__dly_c2:
	LDI	R18, 1
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
_dly_S2:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_S2
	RET

__dly_c106:
	LDI	R18, 105
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
_dly_S106:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_S106
	RET

__dly_c133:
	LDI	R18, 132
	LDI	R19, 0
	LDI	R20, 0
	LDI	R21, 0
_dly_S133:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_S133
	RET

__dly_c293:
	LDI	R18, 36
	LDI	R19, 1
	LDI	R20, 0
	LDI	R21, 0
_dly_S293:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_S293
	RET

__dly_c5333:
	LDI	R18, 212
	LDI	R19, 20
	LDI	R20, 0
	LDI	R21, 0
_dly_S5333:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_S5333
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 76, 67, 68, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 79, 75, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 0
.balign 2
	.balign 2
