; Generated by pymcuc for 
; volatile 'edge' -> GPIOR @ 0x3E (ISR-shared, auto-promoted)
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_88, _stack_base + 1
.equ tmp_90, _stack_base + 2
.equ tmp_91, _stack_base + 3
.equ tmp_93, _stack_base + 6
.equ tmp_94, _stack_base + 7
.equ _s610f894f, _stack_base + 9

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	pcint0_isr
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt


; --- PyMCU AVR Math Runtime ---
; -----------------------------------------------------------------------------
; PyMCU AVR Math Runtime
; -----------------------------------------------------------------------------
;
; __div8: Unsigned 8-bit Division
;   Input:  R24 (Dividend), R18 (Divisor)
;   Output: R24 (Quotient), R25 (Remainder)
;   Clobbers: R25
;
; __mod8: Unsigned 8-bit Modulo
;   Input:  R24 (Dividend), R18 (Divisor)
;   Output: R24 (Remainder)
;   Clobbers: R25
;
; -----------------------------------------------------------------------------

__div8:
    push r16
    ldi r16, 8      ; 8 iterations: one per dividend bit
    clr r25         ; Remainder = 0
    clc             ; Clear carry

__div8_loop:
    rol r24         ; Shift dividend left, MSB into Carry
    rol r25         ; Shift remainder left, Carry into LSB
    brcs __div8_sub ; Remainder overflowed (>= 256) -> must subtract
    cp r25, r18     ; Compare Remainder with Divisor
    brcs __div8_next; Remainder < Divisor: quotient bit = 0

__div8_sub:
    sub r25, r18    ; Remainder -= Divisor
    sec             ; Quotient bit = 1
    rjmp __div8_dec

__div8_next:
    clc             ; Quotient bit = 0

__div8_dec:
    dec r16
    brne __div8_loop

    rol r24         ; Final ROL shifts last quotient bit into R24

    pop r16
    ret

__mod8:
    rcall __div8
    mov r24, r25    ; Move remainder to result register
    ret

; -----------------------------------------------------------------------------
; __divs8 / __mods8: SIGNED 8-bit floor division and modulo (Python semantics).
;   Input:  R24 (Dividend a), R18 (Divisor b)   -- both signed
;   Output: __divs8 -> R24 = floor(a/b)
;           __mods8 -> R24 = a - b*floor(a/b)   (remainder takes the sign of b)
;   Net clobber: R24, R25 (same as __div8; R16/R17/R19 are push/pop-restored).
;
; Strategy: divide the magnitudes with the unsigned core, give the truncating
; quotient/remainder their signs, then apply the single Python floor correction
; (when the signs differ and the remainder is non-zero: q -= 1; r += b).
; -----------------------------------------------------------------------------
__divmods8:
    push r16
    push r17
    push r19
    mov  r19, r24       ; r19 = original a (sign of dividend)
    mov  r17, r18       ; r17 = original b (sign + floor add)
    sbrc r24, 7
    neg  r24            ; |a|
    sbrc r18, 7
    neg  r18            ; |b|
    rcall __div8        ; R24 = |a|/|b| (uq), R25 = |a|%|b| (ur); R18 preserved
    sbrc r19, 7
    neg  r25            ; truncating remainder takes the sign of a
    mov  r16, r19
    eor  r16, r17       ; r16 bit7 = 1 when signs differ (quotient is negative)
    sbrc r16, 7
    neg  r24            ; truncating quotient sign
    sbrs r16, 7
    rjmp __divmods8_done    ; signs equal -> trunc == floor
    tst  r25
    breq __divmods8_done    ; exact -> no correction
    dec  r24            ; floor: q -= 1
    add  r25, r17       ;        r += b
__divmods8_done:
    pop  r19
    pop  r17
    pop  r16
    ret

__divs8:
    rcall __divmods8
    ret                 ; quotient already in R24

__mods8:
    rcall __divmods8
    mov  r24, r25       ; remainder -> result register
    ret


__bad_interrupt:
	JMP	main

pcint0_isr:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDI	R24, 1
	OUT	0x1E, R24
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
_s4e65a6dd:
	STD	Y+9, R24
	STD	Y+10, R25
	LDI	R24, 0
	MOV	R4, R24
	LDD	R30, Y+9
	LDD	R31, Y+10
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R5, R24
L_154:
	MOV	R24, R5
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R5
	STS	0x00C6, R24
	INC	R4
	LDD	R30, Y+9
	LDD	R31, Y+10
	MOV	R24, R4
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R5, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	CBI	0x04, 0
	SBI	0x05, 0

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDS	R24, 0x0068
	ORI	R24, 1
	STS	0x0068, R24
	LDS	R24, 0x006B
	ORI	R24, 1
	STS	0x006B, R24
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_221:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_221
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 0
	MOV	R3, R24

L_223:

	IN	R24, 0x1E
	CPI	R24, 1
	BRNE	L_225

	LDI	R24, 0
	OUT	0x1E, R24

	SBIS	0x03, 0
	JMP	L_BIT_FALSE_4
	LDI	R24, 1
	JMP	L_BIT_DONE_5
L_BIT_FALSE_4:
	LDI	R24, 0
L_BIT_DONE_5:
	CPI	R24, 0
	BRNE	L_226

	INC	R3

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd

	MOV	R24, R3
	LDI	R18, 10
	CALL	__div8
	CLR	R25
	ADIW	R24, 48
	STD	Y+3, R24
	STD	Y+4, R25
	MOV	R2, R24
L_233:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_233
	MOV	R24, R2
	STS	0x00C6, R24

	MOV	R24, R3
	LDI	R18, 10
	CALL	__mod8
	CLR	R25
	ADIW	R24, 48
	STD	Y+7, R24
	STD	Y+8, R25
	MOV	R2, R24
L_237:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_237
	MOV	R24, R2
	STS	0x00C6, R24

L_241:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_241
	LDI	R24, 10
	STS	0x00C6, R24
L_226:
L_225:
	JMP	L_223

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 80, 67, 73, 78, 84, 32, 67, 79, 85, 78, 84, 69, 82, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 67, 79, 85, 78, 84, 58, 0
.balign 2
	.balign 2
