; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_95, _stack_base + 0
.equ tmp_99, _stack_base + 2
.equ tmp_103, _stack_base + 3
.equ tmp_107, _stack_base + 4
.equ _s610f894f, _stack_base + 5
.equ tmp_93, _stack_base + 7

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt


; --- PyMCU AVR Math Runtime ---
; -----------------------------------------------------------------------------
; PyMCU AVR Math Runtime
; -----------------------------------------------------------------------------
;
; __div8: Unsigned 8-bit Division
;   Input:  R24 (Dividend), R18 (Divisor)
;   Output: R24 (Quotient), R25 (Remainder)
;   Clobbers: R25
;
; __mod8: Unsigned 8-bit Modulo
;   Input:  R24 (Dividend), R18 (Divisor)
;   Output: R24 (Remainder)
;   Clobbers: R25
;
; -----------------------------------------------------------------------------

__div8:
    push r16
    ldi r16, 8      ; 8 iterations: one per dividend bit
    clr r25         ; Remainder = 0
    clc             ; Clear carry

__div8_loop:
    rol r24         ; Shift dividend left, MSB into Carry
    rol r25         ; Shift remainder left, Carry into LSB
    brcs __div8_sub ; Remainder overflowed (>= 256) -> must subtract
    cp r25, r18     ; Compare Remainder with Divisor
    brcs __div8_next; Remainder < Divisor: quotient bit = 0

__div8_sub:
    sub r25, r18    ; Remainder -= Divisor
    sec             ; Quotient bit = 1
    rjmp __div8_dec

__div8_next:
    clc             ; Quotient bit = 0

__div8_dec:
    dec r16
    brne __div8_loop

    rol r24         ; Final ROL shifts last quotient bit into R24

    pop r16
    ret

__mod8:
    rcall __div8
    mov r24, r25    ; Move remainder to result register
    ret

; -----------------------------------------------------------------------------
; __divs8 / __mods8: SIGNED 8-bit floor division and modulo (Python semantics).
;   Input:  R24 (Dividend a), R18 (Divisor b)   -- both signed
;   Output: __divs8 -> R24 = floor(a/b)
;           __mods8 -> R24 = a - b*floor(a/b)   (remainder takes the sign of b)
;   Net clobber: R24, R25 (same as __div8; R16/R17/R19 are push/pop-restored).
;
; Strategy: divide the magnitudes with the unsigned core, give the truncating
; quotient/remainder their signs, then apply the single Python floor correction
; (when the signs differ and the remainder is non-zero: q -= 1; r += b).
; -----------------------------------------------------------------------------
__divmods8:
    push r16
    push r17
    push r19
    mov  r19, r24       ; r19 = original a (sign of dividend)
    mov  r17, r18       ; r17 = original b (sign + floor add)
    sbrc r24, 7
    neg  r24            ; |a|
    sbrc r18, 7
    neg  r18            ; |b|
    rcall __div8        ; R24 = |a|/|b| (uq), R25 = |a|%|b| (ur); R18 preserved
    sbrc r19, 7
    neg  r25            ; truncating remainder takes the sign of a
    mov  r16, r19
    eor  r16, r17       ; r16 bit7 = 1 when signs differ (quotient is negative)
    sbrc r16, 7
    neg  r24            ; truncating quotient sign
    sbrs r16, 7
    rjmp __divmods8_done    ; signs equal -> trunc == floor
    tst  r25
    breq __divmods8_done    ; exact -> no correction
    dec  r24            ; floor: q -= 1
    add  r25, r17       ;        r += b
__divmods8_done:
    pop  r19
    pop  r17
    pop  r16
    ret

__divs8:
    rcall __divmods8
    ret                 ; quotient already in R24

__mods8:
    rcall __divmods8
    mov  r24, r25       ; remainder -> result register
    ret


__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+5, R24
	STD	Y+6, R25
	LDI	R24, 0
	MOV	R5, R24
	LDD	R30, Y+5
	LDD	R31, Y+6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
L_164:
	MOV	R24, R8
	CPI	R24, 0
	BREQ	L_165
L_167:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_167
	MOV	R24, R8
	STS	0x00C6, R24
	INC	R5
	LDD	R30, Y+5
	LDD	R31, Y+6
	MOV	R24, R5
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
	JMP	L_164
L_165:
	RET
validate_sensor:
	MOV	R10, R24

	CPI	R24, 101
	BRLO	L_194

	LDI	R22, 1
	SET
	RET
L_194:

	MOV	R24, R10
	CLT
	RET
safe_divide:
	MOV	R14, R24
	MOV	R6, R22

	MOV	R24, R6
	CPI	R24, 0
	BRNE	L_195

	LDI	R22, 1
	SET
	RET
L_195:

	MOV	R24, R6
	TST	R24
	BRNE	L_196
	LDI	R22, 6
	SET
	RET
L_196:
	MOV	R24, R14
	MOV	R18, R6
	CALL	__div8
	CLT
	RET
bounds_check:
	MOV	R7, R24
	MOV	R11, R22

	MOV	R18, R11
	CP	R24, R18
	BRLO	L_197

	LDI	R22, 3
	SET
	RET
L_197:

	MOV	R24, R7
	CLT
	RET
raise_by_type:
	MOV	R9, R24

	CPI	R24, 1
	BRNE	L_198

	LDI	R22, 1
	SET
	RET
L_198:

	MOV	R24, R9
	CPI	R24, 2
	BRNE	L_199

	LDI	R22, 2
	SET
	RET
L_199:

	LDI	R24, 0
	CLT
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0


	LDI	R24, 200
	CALL	validate_sensor
	BRTS	L_210

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	BRTS	L_210
	CALL	__pymcu_outline_0
	JMP	L_211
L_210:
	MOV	R24, R22
	CPI	R24, 1
	BRNE	L_218

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_211
L_218:
	CALL	__pymcu_unhandled_exn
L_211:


	LDI	R24, 10
	LDI	R22, 0
	CALL	safe_divide
	BRTS	L_225

	LDI	R24, lo8(__flash___cstr_3)
	LDI	R25, hi8(__flash___cstr_3)
	CALL	_s4e65a6dd
	BRTS	L_225
	CALL	__pymcu_outline_0
	JMP	L_226
L_225:
	MOV	R24, R22
	CPI	R24, 1
	BRNE	L_233

	LDI	R24, lo8(__flash___cstr_4)
	LDI	R25, hi8(__flash___cstr_4)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_226
L_233:
	CALL	__pymcu_unhandled_exn
L_226:


	LDI	R24, 7
	LDI	R22, 4
	CALL	bounds_check
	BRTS	L_240

	LDI	R24, lo8(__flash___cstr_5)
	LDI	R25, hi8(__flash___cstr_5)
	CALL	_s4e65a6dd
	BRTS	L_240
	CALL	__pymcu_outline_0
	JMP	L_241
L_240:
	MOV	R24, R22
	CPI	R24, 3
	BRNE	L_248

	LDI	R24, lo8(__flash___cstr_6)
	LDI	R25, hi8(__flash___cstr_6)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_241
L_248:
	CALL	__pymcu_unhandled_exn
L_241:


	LDI	R24, 2
	CALL	raise_by_type
	BRTS	L_255

	LDI	R24, lo8(__flash___cstr_7)
	LDI	R25, hi8(__flash___cstr_7)
	CALL	_s4e65a6dd
	BRTS	L_255
	CALL	__pymcu_outline_0
	JMP	L_256
L_255:
	MOV	R24, R22
	CPI	R24, 1
	BRNE	L_263

	LDI	R24, lo8(__flash___cstr_8)
	LDI	R25, hi8(__flash___cstr_8)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_256
L_263:
	MOV	R24, R22
	CPI	R24, 2
	BRNE	L_270

	LDI	R24, lo8(__flash___cstr_9)
	LDI	R25, hi8(__flash___cstr_9)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0
	JMP	L_256
L_270:
	CALL	__pymcu_unhandled_exn
L_256:

	LDI	R24, lo8(__flash___cstr_10)
	LDI	R25, hi8(__flash___cstr_10)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_0

L_283:

	LDI	R18, 170
	LDI	R19, 176
	LDI	R20, 40
	LDI	R21, 0
_dly_L0:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_L0
	JMP	L_283
__pymcu_outline_0:
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	LDI	R24, 10
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 69, 82, 82, 45, 72, 65, 78, 68, 76, 73, 78, 71, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 65, 58, 111, 107, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 65, 58, 111, 117, 116, 45, 111, 102, 45, 114, 97, 110, 103, 101, 0
.balign 2
	.balign 2
__flash___cstr_3:
	.byte 66, 58, 111, 107, 0
.balign 2
	.balign 2
__flash___cstr_4:
	.byte 66, 58, 100, 105, 118, 45, 98, 121, 45, 122, 101, 114, 111, 0
.balign 2
	.balign 2
__flash___cstr_5:
	.byte 67, 58, 111, 107, 0
.balign 2
	.balign 2
__flash___cstr_6:
	.byte 67, 58, 111, 117, 116, 45, 111, 102, 45, 98, 111, 117, 110, 100, 115, 0
.balign 2
	.balign 2
__flash___cstr_7:
	.byte 68, 58, 111, 107, 0
.balign 2
	.balign 2
__flash___cstr_8:
	.byte 68, 58, 118, 97, 108, 45, 101, 114, 114, 0
.balign 2
	.balign 2
__flash___cstr_9:
	.byte 68, 58, 116, 121, 112, 101, 45, 101, 114, 114, 0
.balign 2
	.balign 2
__flash___cstr_10:
	.byte 68, 79, 78, 69, 0
.balign 2
	.balign 2
; ── Exception runtime ──────────────────────────────────────────────────────
__exn_str_1:
    .byte 69, 58, 86, 97, 108, 117, 101, 69, 114, 114, 111, 114, 13, 10, 0
.balign 2
__exn_str_2:
    .byte 69, 58, 84, 121, 112, 101, 69, 114, 114, 111, 114, 13, 10, 0
.balign 2
__exn_str_3:
    .byte 69, 58, 73, 110, 100, 101, 120, 69, 114, 114, 111, 114, 13, 10, 0
.balign 2
__exn_str_6:
    .byte 69, 58, 69, 120, 99, 101, 112, 116, 105, 111, 110, 54, 13, 10, 0
.balign 2
    .balign 2

__pymcu_unhandled_exn:
    lds   R16, 0xC1
    sbrs  R16, 3
    rjmp  __exn_halt
    cpi   R22, 1
    breq  __exn_load_1
    cpi   R22, 2
    breq  __exn_load_2
    cpi   R22, 3
    breq  __exn_load_3
    cpi   R22, 6
    breq  __exn_load_6
    rjmp  __exn_halt
__exn_load_1:
    ldi   R30, lo8(__exn_str_1)
    ldi   R31, hi8(__exn_str_1)
    rjmp  __exn_print_loop
__exn_load_2:
    ldi   R30, lo8(__exn_str_2)
    ldi   R31, hi8(__exn_str_2)
    rjmp  __exn_print_loop
__exn_load_3:
    ldi   R30, lo8(__exn_str_3)
    ldi   R31, hi8(__exn_str_3)
    rjmp  __exn_print_loop
__exn_load_6:
    ldi   R30, lo8(__exn_str_6)
    ldi   R31, hi8(__exn_str_6)
__exn_print_loop:
    lpm   R16, Z+
    tst   R16
    breq  __exn_halt
__exn_wait_udre:
    lds   R17, 0xC0
    sbrs  R17, 5
    rjmp  __exn_wait_udre
    sts   0xC6, R16
    rjmp  __exn_print_loop
__exn_halt:
    cli
    rjmp  .-2

