; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 1

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+1, R24
	STD	Y+2, R25
	LDI	R24, 0
	MOV	R2, R24
	LDD	R30, Y+1
	LDD	R31, Y+2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R4, R24
L_154:
	MOV	R24, R4
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R4
	STS	0x00C6, R24
	INC	R2
	LDD	R30, Y+1
	LDD	R31, Y+2
	MOV	R24, R2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R4, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0

	LDI	R24, 84
	CALL	__pymcu_outline_0

	LDI	R24, 101
	CALL	__pymcu_outline_0

	LDI	R24, 115
	CALL	__pymcu_outline_0

	LDI	R24, 116
	CALL	__pymcu_outline_0

	LDI	R24, 10
	CALL	__pymcu_outline_0

L_215:

L_219:
	LDS	R24, 0x00C0
	ANDI	R24, 128
	BREQ	L_219
	LDS	R24, 0x00C6
	MOV	R3, R24

L_223:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_223
	MOV	R24, R3
	STS	0x00C6, R24
	JMP	L_215
__pymcu_outline_0:
	MOV	R5, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R5
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 72, 101, 108, 108, 111, 44, 32, 80, 121, 77, 67, 85, 33, 10, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 85, 65, 82, 84, 32, 115, 116, 114, 105, 110, 103, 32, 115, 117, 112, 112, 111, 114, 116, 32, 119, 111, 114, 107, 115, 33, 0
.balign 2
	.balign 2
