; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_96, _stack_base + 4
.equ tmp_100, _stack_base + 5
.equ tmp_102, _stack_base + 7
.equ tmp_104, _stack_base + 10
.equ tmp_107, _stack_base + 13
.equ tmp_109, _stack_base + 15
.equ tmp_112, _stack_base + 17
.equ _s610f894f, _stack_base + 19

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+19, R24
	STD	Y+20, R25
	LDI	R24, 0
	MOV	R7, R24
	LDD	R30, Y+19
	LDD	R31, Y+20
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R10, R24
L_162:
	MOV	R24, R10
	CPI	R24, 0
	BREQ	L_163
	CALL	__pymcu_outline_0
	INC	R7
	LDD	R30, Y+19
	LDD	R31, Y+20
	MOV	R24, R7
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R10, R24
	JMP	L_162
L_163:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 72
	STS	0x00B8, R24
	LDI	R24, 4
	STS	0x00BC, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_1

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_1

	LDI	R24, 0
	MOV	R6, R24

	LDI	R24, 1
	MOV	R3, R24

L_212:
	MOV	R24, R3
	CPI	R24, 128
	BRLO	L_BR_SKIP_1
	JMP	L_213
L_BR_SKIP_1:

	LDI	R24, 164
	STS	0x00BC, R24
L_218:
	LDS	R24, 0x00BC
	ANDI	R24, 128
	BREQ	L_218
	LDS	R24, 0x00B9
	ANDI	R24, 248
	MOV	R9, R24
	CPI	R24, 8
	BRNE	L_221
	MOV	R24, R3
	LSL	R24
	STS	0x00BB, R24
	LDI	R24, 132
	STS	0x00BC, R24
L_222:
	LDS	R24, 0x00BC
	ANDI	R24, 128
	BREQ	L_222
	LDS	R24, 0x00B9
	ANDI	R24, 248
	MOV	R8, R24
	LDI	R24, 148
	STS	0x00BC, R24
	MOV	R24, R8
	CPI	R24, 24
	BRNE	L_224
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_217
L_224:
	JMP	L_220
L_221:
	LDI	R24, 148
	STS	0x00BC, R24
L_220:
	LDI	R24, 0
	MOV	R16, R24
L_217:
	MOV	R24, R16
	TST	R24
	BREQ	L_214

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd

	MOV	R24, R3
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 15
	MOV	R4, R24

	CPI	R24, 10
	BRSH	L_227

	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_226
L_227:

	MOV	R24, R4
	CLR	R25
	ADIW	R24, 55
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_226:

	MOV	R24, R3
	ANDI	R24, 15
	MOV	R5, R24

	CPI	R24, 10
	BRSH	L_237

	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_236
L_237:

	MOV	R24, R5
	CLR	R25
	ADIW	R24, 55
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_236:

	CALL	__pymcu_outline_1

	INC	R6
	MOV	R24, R6
L_214:

	INC	R3
	MOV	R24, R3
	JMP	L_212
L_213:

	LDI	R24, lo8(__flash___cstr_3)
	LDI	R25, hi8(__flash___cstr_3)
	CALL	_s4e65a6dd

	MOV	R24, R6
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0

	CALL	__pymcu_outline_1

L_259:
	JMP	L_259
__pymcu_outline_0:
	MOV	R11, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R11
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
__pymcu_outline_1.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_1.L0
	LDI	R24, 10
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 73, 50, 67, 32, 83, 67, 65, 78, 78, 69, 82, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 83, 99, 97, 110, 110, 105, 110, 103, 32, 48, 120, 48, 49, 45, 48, 120, 55, 70, 46, 46, 46, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 70, 79, 85, 78, 68, 32, 48, 120, 0
.balign 2
	.balign 2
__flash___cstr_3:
	.byte 68, 111, 110, 101, 46, 32, 70, 111, 117, 110, 100, 58, 32, 0
.balign 2
	.balign 2
