; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _ssd1306_buf, _stack_base + 2
.equ tmp_116, _stack_base + 1026
.equ tmp_118, _stack_base + 1027
.equ tmp_123, _stack_base + 1029
.equ tmp_125, _stack_base + 1030
.equ _s610f894f, _stack_base + 1032
.equ tmp_107, _stack_base + 1034
.equ tmp_93, _stack_base + 1037
.equ tmp_94, _stack_base + 1038
.equ tmp_96, _stack_base + 1040
.equ tmp_97, _stack_base + 1041
.equ tmp_98, _stack_base + 1042
.equ tmp_99, _stack_base + 1043

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STS	0x0508, R24
	STS	0x0509, R25
	LDI	R24, 0
	MOV	R5, R24
	LDS	R30, 0x0508
	MOV	R31, R25
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
L_154:
	MOV	R24, R8
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R8
	STS	0x00C6, R24
	INC	R5
	LDS	R30, 0x0508
	LDS	R31, 0x0509
	MOV	R24, R5
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
	JMP	L_154
L_155:
	RET
_s9c096ac4:
	LDI	R24, 164
	STS	0x00BC, R24
L_184:
	LDS	R24, 0x00BC
	ANDI	R24, 128
	BREQ	L_184
	LDS	R24, 0x00B9
	ANDI	R24, 248
	MOV	R6, R24
	RET
_s8b5d0640:
	LDI	R24, 148
	STS	0x00BC, R24
	RET
_s4cb7a3c7:
	MOV	R12, R24
	STS	0x00BB, R24
	LDI	R24, 132
	STS	0x00BC, R24
L_186:
	LDS	R24, 0x00BC
	ANDI	R24, 128
	BREQ	L_186
	LDS	R24, 0x00B9
	ANDI	R24, 248
	MOV	R7, R24
	RET
ssd1306_cmd:
	MOV	R9, R24
	MOV	R10, R22

	CALL	_s9c096ac4

	MOV	R24, R9
	CLR	R25
	LSL	R24
	ROL	R25
	LDI	R18, 254
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	STS	0x0510, R24
	CALL	_s4cb7a3c7

	LDI	R24, 0
	CALL	_s4cb7a3c7

	MOV	R24, R10
	CALL	_s4cb7a3c7

	CALL	_s8b5d0640
	RET
ssd1306_init:
	MOV	R11, R24
	LDI	R24, 0
	MOV	R4, R24
L_192:
	MOV	R24, R4
	CPI	R24, 25
	BRSH	L_193
	LDI	R30, lo8(__flash__SSD1306_INIT)
	LDI	R31, hi8(__flash__SSD1306_INIT)
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R22, R24
	MOV	R24, R11
	CALL	ssd1306_cmd
	INC	R4
	JMP	L_192
L_193:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 72
	STS	0x00B8, R24
	LDI	R24, 4
	STS	0x00BC, R24


	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_207:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_207
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 60
	CALL	ssd1306_init

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
L_215:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_215
	LDI	R24, 10
	STS	0x00C6, R24

	LDI	R24, 0
	LDI	R25, 0
	MOV	R2, R24
	MOV	R3, R25
L_218:
	MOV	R24, R2
	MOV	R25, R3
	LDI	R18, 0
	LDI	R19, 4
	CP	R24, R18
	CPC	R25, R19
	BRSH	L_219
	LDI	R24, 0
	MOV	R18, R24
; ArrayStore variable index via Z
	MOV	R24, R2
	LDI	R30, lo8(258)
	LDI	R31, hi8(258)
	ADD	R30, R24
	ADC	R31, R1
	ST	Z, R18
	ADIW	R24, 1
	MOV	R2, R24
	MOV	R3, R25
	JMP	L_218
L_219:

	LDD	R24, Y+2
	CLR	R25
	LDI	R18, 1
	LDI	R19, 0
	OR	R24, R18
	OR	R25, R19
	STS	0x0503, R24
	STS	0x0504, R25
	STD	Y+2, R24

	LDS	R24, 0x0501
	CLR	R25
	LDI	R18, 128
	OR	R24, R18
	OR	R25, R19
	STS	0x0506, R24
	STS	0x0507, R25
	STS	0x0501, R24

L_230:
	JMP	L_230

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 79, 76, 69, 68, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 79, 75, 0
.balign 2
	.balign 2
__flash__SSD1306_INIT:
	.byte 174, 213, 128, 168, 63, 211, 0, 64, 141, 20, 32, 0, 161, 200, 218, 18, 129, 207, 217, 241, 219, 64, 164, 166, 175
.balign 2
	.balign 2
