; Generated by pymcuc for 
; volatile 'rx' -> GPIOR @ 0x3E (ISR-shared, auto-promoted)
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_100, _stack_base + 3
.equ tmp_102, _stack_base + 6
.equ tmp_103, _stack_base + 8
.equ tmp_105, _stack_base + 12
.equ tmp_107, _stack_base + 14
.equ tmp_108, _stack_base + 16
.equ _s610f894f, _stack_base + 20

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	on_event
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

on_event:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDS	R24, 0x00B9
	ANDI	R24, 248
	MOV	R5, R24

	CPI	R24, 96
	BRNE	L_193

	LDI	R24, 196
	STS	0x00BC, R24
	JMP	L_192
L_193:
	MOV	R24, R5
	CPI	R24, 128
	BRNE	L_194

	LDS	R24, 0x00BB
	OUT	0x1E, R24

	LDI	R24, 196
	STS	0x00BC, R24
	JMP	L_192
L_194:
	MOV	R24, R5
	CPI	R24, 160
	BRNE	L_195

	LDI	R24, 196
	STS	0x00BC, R24
	JMP	L_192
L_195:

	LDI	R24, 196
	STS	0x00BC, R24
L_192:
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
_s4e65a6dd:
	STD	Y+20, R24
	STD	Y+21, R25
	LDI	R24, 0
	MOV	R7, R24
	LDD	R30, Y+20
	LDD	R31, Y+21
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
L_162:
	MOV	R24, R8
	CPI	R24, 0
	BREQ	L_163
	CALL	__pymcu_outline_0
	INC	R7
	LDD	R30, Y+20
	LDD	R31, Y+21
	MOV	R24, R7
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
	JMP	L_162
L_163:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 132
	STS	0x00BA, R24
	LDI	R24, 68
	STS	0x00BC, R24

	LDS	R24, 0x00BC
	ORI	R24, 1
	STS	0x00BC, R24
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_210:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_210
	LDI	R24, 10
	STS	0x00C6, R24

L_212:

	IN	R24, 0x1E
	CPI	R24, 0
	BRNE	L_BR_SKIP_5
	JMP	L_214
L_BR_SKIP_5:

	IN	R24, 0x1E
	MOV	R6, R24

	LDI	R24, 0
	OUT	0x1E, R24

	MOV	R24, R6
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	MOV	R3, R24
	MOV	R24, R6
	ANDI	R24, 15
	MOV	R4, R24
	MOV	R24, R3
	CPI	R24, 10
	BRSH	L_217
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_216
L_217:
	MOV	R24, R3
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_216:
	MOV	R24, R4
	CPI	R24, 10
	BRSH	L_227
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_226
L_227:
	MOV	R24, R4
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+16, R24
	STD	Y+17, R25
	STD	Y+18, R22
	STD	Y+19, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_226:

L_238:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_238
	LDI	R24, 10
	STS	0x00C6, R24
L_214:
	JMP	L_212
__pymcu_outline_0:
	MOV	R9, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R9
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 73, 50, 67, 73, 0
.balign 2
	.balign 2
