; Generated by pymcuc for 
; volatile 'pymcu_hal_avr_uart_avr__rx_tail' -> GPIOR @ 0x3E (ISR-shared, auto-promoted)
; volatile 'pymcu_hal_avr_uart_avr__rx_head' -> GPIOR @ 0x4A (ISR-shared, auto-promoted)
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_90, _stack_base + 0
.equ tmp_92, _stack_base + 1
.equ _rx_buf, _stack_base + 29
.equ tmp_94, _stack_base + 19
.equ _s610f894f, _stack_base + 22
.equ tmp_86, _stack_base + 26

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	on_rx
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

on_rx:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R17
	PUSH	R18
	PUSH	R19
	PUSH	R24
	PUSH	R25
	PUSH	R30
	PUSH	R31
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1

	IN	R24, 0x2A
	LDS	R25, 0x004B
	ADIW	R24, 1
	MOV	R16, R24
	MOV	R17, R25
	LDI	R18, 15
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	MOV	R2, R24
	IN	R18, 0x1E
	CP	R24, R18
	BREQ	L_187
	LDS	R24, 0x00C6
	MOV	R18, R24
; ArrayStore variable index via Z
	IN	R24, 0x2A
	LDI	R30, lo8(285)
	LDI	R31, hi8(285)
	ADD	R30, R24
	ADC	R31, R1
	ST	Z, R18
	MOV	R24, R2
	OUT	0x2A, R24
L_187:
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R31
	POP	R30
	POP	R25
	POP	R24
	POP	R19
	POP	R18
	POP	R17
	POP	R16
	POP	R1
	RETI
_s4e65a6dd:
	STD	Y+22, R24
	STD	Y+23, R25
	LDI	R24, 0
	MOV	R3, R24
	LDD	R30, Y+22
	LDD	R31, Y+23
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R6, R24
L_154:
	MOV	R24, R6
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R6
	STS	0x00C6, R24
	INC	R3
	LDD	R30, Y+22
	LDD	R31, Y+23
	MOV	R24, R3
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R6, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDS	R24, 0x00C1
	ORI	R24, 128
	STS	0x00C1, R24
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_197:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_197
	LDI	R24, 10
	STS	0x00C6, R24

L_199:

	IN	R24, 0x2A
	IN	R18, 0x1E
	CP	R24, R18
	BREQ	L_204
	LDI	R24, 1
	MOV	R16, R24
	JMP	L_203
L_204:
	LDI	R24, 0
	MOV	R16, R24
L_203:
	MOV	R24, R16
	TST	R24
	BREQ	L_201

	IN	R24, 0x2A
	IN	R18, 0x1E
	CP	R24, R18
	BRNE	L_207
	LDI	R24, 0
	MOV	R16, R24
	JMP	L_206
L_207:
; ArrayLoad variable index via Z
	IN	R24, 0x1E
	LDI	R30, lo8(285)
	LDI	R31, hi8(285)
	ADD	R30, R24
	ADC	R31, R1
	LD	R24, Z
	MOV	R4, R24
	IN	R24, 0x1E
	LDS	R25, 0x003F
	ADIW	R24, 1
	STD	Y+19, R24
	STD	Y+20, R25
	LDI	R18, 15
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	OUT	0x1E, R24
	MOV	R24, R4
	MOV	R16, R24
L_206:
	MOV	R24, R16
	MOV	R5, R24

L_210:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_210
	MOV	R24, R5
	STS	0x00C6, R24
L_201:
	JMP	L_199

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 82, 88, 73, 82, 81, 0
.balign 2
	.balign 2
