; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_10, _stack_base + 3
.equ tmp_18, _stack_base + 7

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 1
	SBI	0x04, 2
	LDI	R24, 0
	STS	0x0081, R24
	LDI	R24, 156
	STS	0x0087, R24
	LDI	R24, 63
	STS	0x0086, R24
	LDI	R24, 7
	STS	0x0089, R24
	LDI	R24, 207
	STS	0x0088, R24
	LDI	R24, 7
	MOV	R5, R24
	STS	0x008B, R24
	LDI	R24, 207
	MOV	R6, R24
	STS	0x008A, R24
	LDI	R24, 162
	STS	0x0080, R24
	LDI	R24, 26
	STS	0x0081, R24

L_15:

	LDI	R24, 0
	MOV	R2, R24

L_17:
	MOV	R24, R2
	CPI	R24, 181
	BRSH	L_18

	CLR	R25
	LDI	R18, 11
	LDI	R19, 0
	MUL	R24, R18
	MOV	R20, R0
	MOV	R21, R1
	MUL	R24, R19
	ADD	R21, R0
	MUL	R25, R18
	ADD	R21, R0
	MOV	R16, R20
	MOV	R17, R21
	CLR	R1
	LDI	R24, 207
	LDI	R25, 7
	ADD	R24, R16
	ADC	R25, R17
	MOV	R3, R24
	MOV	R4, R25
	MOV	R24, R25
	CLR	R25
	MOV	R5, R24
	STS	0x0089, R24
	MOV	R24, R3
	MOV	R6, R24
	STS	0x0088, R24

	CALL	__dly_c40000

	INC	R2
	JMP	L_17
L_18:

L_26:
	MOV	R24, R2
	CPI	R24, 1
	BRLO	L_27

	DEC	R2

	MOV	R24, R2
	CLR	R25
	LDI	R18, 11
	LDI	R19, 0
	MUL	R24, R18
	MOV	R20, R0
	MOV	R21, R1
	MUL	R24, R19
	ADD	R21, R0
	MUL	R25, R18
	ADD	R21, R0
	MOV	R16, R20
	MOV	R17, R21
	CLR	R1
	LDI	R24, 207
	LDI	R25, 7
	ADD	R24, R16
	ADC	R25, R17
	MOV	R3, R24
	MOV	R4, R25
	MOV	R24, R25
	CLR	R25
	MOV	R5, R24
	STS	0x0089, R24
	MOV	R24, R3
	MOV	R6, R24
	STS	0x0088, R24

	CALL	__dly_c40000
	JMP	L_26
L_27:
	JMP	L_15

__dly_c40000:
	LDI	R18, 63
	LDI	R19, 156
	LDI	R20, 0
	LDI	R21, 0
_dly_S40000:
	SUBI	R18, 1
	SBCI	R19, 0
	SBCI	R20, 0
	SBCI	R21, 0
	BRNE	_dly_S40000
	RET
