; Generated by pymcuc for 
; volatile 'btn_f' -> GPIOR @ 0x3E (ISR-shared, auto-promoted)
; volatile 'ovf_f' -> GPIOR @ 0x4A (ISR-shared, auto-promoted)
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_94, _stack_base + 8
.equ inline2_adc_read_result, _stack_base + 12
.equ tmp_97, _stack_base + 14
.equ _s610f894f, _stack_base + 16
.equ _s500f6e8c, _stack_base + 19
.equ __pymcu_outline_0_p0, _stack_base + 39
.equ __pymcu_outline_3_v1, _stack_base + 17
.equ __pymcu_outline_3_v4, _stack_base + 20
.equ __pymcu_outline_3_v5, _stack_base + 22
.equ __pymcu_outline_3_v6, _stack_base + 24
.equ __pymcu_outline_3_v7, _stack_base + 28
.equ __pymcu_outline_3_v8, _stack_base + 30
.equ __pymcu_outline_3_v9, _stack_base + 32
.equ __pymcu_outline_2_p0, _stack_base + 36

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	int0_isr
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	timer0_ovf_isr
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

timer0_ovf_isr:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDI	R24, 1
	OUT	0x2A, R24
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
int0_isr:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDI	R24, 1
	OUT	0x1E, R24
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
_s4e65a6dd:
	STD	Y+16, R24
	STD	Y+17, R25
	LDI	R24, 0
	MOV	R10, R24
	LDD	R30, Y+16
	LDD	R31, Y+17
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+19, R24
L_154:
	LDD	R24, Y+19
	CPI	R24, 0
	BREQ	L_155
	LDD	R24, Y+19
	CALL	__pymcu_outline_0
	INC	R10
	LDD	R30, Y+16
	LDD	R31, Y+17
	MOV	R24, R10
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	STD	Y+19, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 5

	CBI	0x0A, 2
	SBI	0x0B, 2

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 64
	STS	0x007C, R24
	LDI	R24, 135
	STS	0x007A, R24

	LDI	R24, 0
	OUT	0x24, R24
	LDI	R24, 4
	OUT	0x25, R24

	LDS	R24, 0x006E
	ORI	R24, 1
	STS	0x006E, R24
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDS	R24, 0x0069
	ANDI	R24, 254
	STS	0x0069, R24
	LDS	R24, 0x0069
	ORI	R24, 2
	STS	0x0069, R24
	SBI	0x1D, 0
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_1

	LDI	R24, 0
	MOV	R2, R24

	MOV	R3, R24

	LDI	R24, 255
	MOV	R8, R24

	LDI	R24, 0
	MOV	R7, R24

	LDI	R24, 1
	MOV	R4, R24

	LDI	R24, 0
	MOV	R9, R24

L_279:

	IN	R24, 0x2A
	CPI	R24, 1
	BREQ	L_BR_SKIP_1
	JMP	L_281
L_BR_SKIP_1:

	LDI	R24, 0
	OUT	0x2A, R24

	SBI	0x15, 0

	INC	R9
	MOV	R24, R9

	CPI	R24, 64
	BREQ	L_BR_SKIP_2
	JMP	L_282
L_BR_SKIP_2:

	LDI	R24, 0
	MOV	R9, R24

	LDS	R24, 0x007A
	ORI	R24, 64
	STS	0x007A, R24
L_285:
	LDS	R24, 0x007A
	ANDI	R24, 64
	BRNE	L_285
	LDS	R24, 0x0078
	MOV	R14, R24
	LDS	R24, 0x0079
	MOV	R13, R24
	CLR	R25
	CLR	R22
	CLR	R23
	MOV	R25, R24
	CLR	R24
	STD	Y+8, R24
	STD	Y+9, R25
	STD	Y+10, R22
	STD	Y+11, R23
	MOV	R24, R14
	CLR	R25
	LDD	R18, Y+8
	LDD	R19, Y+9
	ADD	R24, R18
	ADC	R25, R19
	STD	Y+12, R24
	STD	Y+13, R25

	LSR	R25
	ROR	R24
	LSR	R25
	ROR	R24
	MOV	R2, R24

	MOV	R18, R8
	CP	R24, R18
	BRSH	L_287

	MOV	R8, R24
L_287:

	MOV	R24, R2
	MOV	R18, R7
	CP	R24, R18
	BRLO	L_288
	BREQ	L_288

	MOV	R7, R24
L_288:

	MOV	R24, R3
	CLR	R25
	MOV	R18, R2
	CLR	R19
	ADD	R24, R18
	ADC	R25, R19
	LSR	R25
	ROR	R24
	MOV	R3, R24

	SBI	0x03, 5

	MOV	R24, R4
	CPI	R24, 1
	BRNE	L_291

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd

	MOV	R24, R2
	CALL	__pymcu_outline_3

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd

	MOV	R24, R3
	CALL	__pymcu_outline_3

	LDI	R24, lo8(__flash___cstr_3)
	LDI	R25, hi8(__flash___cstr_3)
	CALL	_s4e65a6dd

	MOV	R24, R8
	CALL	__pymcu_outline_3

	LDI	R24, lo8(__flash___cstr_4)
	LDI	R25, hi8(__flash___cstr_4)
	CALL	_s4e65a6dd

	MOV	R24, R7
	CALL	__pymcu_outline_3

	CALL	__pymcu_outline_1
	JMP	L_290
L_291:

	MOV	R24, R3
	CALL	__pymcu_outline_3

	CALL	__pymcu_outline_1
L_290:
L_282:
L_281:

	IN	R24, 0x1E
	CPI	R24, 1
	BRNE	L_409

	LDI	R24, 0
	OUT	0x1E, R24

	MOV	R24, R4
	CPI	R24, 1
	BRNE	L_411

	LDI	R24, 0
	MOV	R4, R24

	LDI	R24, lo8(__flash___cstr_5)
	LDI	R25, hi8(__flash___cstr_5)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_1
	JMP	L_410
L_411:

	LDI	R24, 1
	MOV	R4, R24

	LDI	R24, lo8(__flash___cstr_6)
	LDI	R25, hi8(__flash___cstr_6)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_1
L_410:
L_409:
	JMP	L_279
__pymcu_outline_0:
	STD	Y+39, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	LDD	R24, Y+39
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
__pymcu_outline_1.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_1.L0
	LDI	R24, 10
	STS	0x00C6, R24
	RET
__pymcu_outline_2:
	STD	Y+36, R24
	STD	Y+37, R25
	MOV	R11, R24
	CALL	__pymcu_outline_0
	RET
__pymcu_outline_3:
	MOV	R12, R24
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 15
	MOV	R5, R24
	MOV	R24, R12
	ANDI	R24, 15
	MOV	R6, R24
	MOV	R24, R5
	CPI	R24, 10
	BRSH	__pymcu_outline_3.L0
	CLR	R25
	ADIW	R24, 48
	CALL	__pymcu_outline_2
	JMP	__pymcu_outline_3.L1
__pymcu_outline_3.L0:
	MOV	R24, R5
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+24, R24
	STD	Y+25, R25
	STD	Y+26, R22
	STD	Y+27, R23
	CALL	__pymcu_outline_2
__pymcu_outline_3.L1:
	MOV	R24, R6
	CPI	R24, 10
	BRSH	__pymcu_outline_3.L2
	CLR	R25
	ADIW	R24, 48
	CALL	__pymcu_outline_2
	JMP	__pymcu_outline_3.L3
__pymcu_outline_3.L2:
	MOV	R24, R6
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+32, R24
	STD	Y+33, R25
	STD	Y+34, R22
	STD	Y+35, R23
	CALL	__pymcu_outline_2
__pymcu_outline_3.L3:
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 83, 69, 78, 83, 79, 82, 32, 68, 65, 83, 72, 66, 79, 65, 82, 68, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 82, 58, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 32, 65, 58, 0
.balign 2
	.balign 2
__flash___cstr_3:
	.byte 32, 76, 58, 0
.balign 2
	.balign 2
__flash___cstr_4:
	.byte 32, 72, 58, 0
.balign 2
	.balign 2
__flash___cstr_5:
	.byte 77, 79, 68, 69, 58, 67, 79, 77, 80, 65, 67, 84, 0
.balign 2
	.balign 2
__flash___cstr_6:
	.byte 77, 79, 68, 69, 58, 86, 69, 82, 66, 79, 83, 69, 0
.balign 2
	.balign 2
