; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_105, _stack_base + 2

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	CBI	0x07, 0
	LDI	R24, 64
	STS	0x007C, R24
	LDI	R24, 135
	STS	0x007A, R24

	CBI	0x0A, 6
	SBI	0x0A, 6
	LDI	R24, 0
	OUT	0x27, R24
	LDI	R24, 131
	OUT	0x24, R24
	LDI	R24, 2
	OUT	0x25, R24

	OUT	0x25, R24

L_318:

	LDS	R24, 0x007A
	ORI	R24, 64
	STS	0x007A, R24
L_324:
	LDS	R24, 0x007A
	ANDI	R24, 64
	BRNE	L_324
	LDS	R24, 0x0078
	MOV	R4, R24
	LDS	R24, 0x0079
	MOV	R3, R24
	CLR	R25
	CLR	R22
	CLR	R23
	MOV	R25, R24
	CLR	R24
	STD	Y+2, R24
	STD	Y+3, R25
	STD	Y+4, R22
	STD	Y+5, R23
	MOV	R24, R4
	CLR	R25
	LDD	R18, Y+2
	LDD	R19, Y+3
	ADD	R24, R18
	ADC	R25, R19
	MOV	R5, R24
	MOV	R6, R25

	LSR	R25
	ROR	R24
	LSR	R25
	ROR	R24
	MOV	R2, R24

	OUT	0x27, R24

L_331:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_331
	MOV	R24, R2
	STS	0x00C6, R24
	JMP	L_318
