; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_100, _stack_base + 5
.equ tmp_102, _stack_base + 6
.equ tmp_107, _stack_base + 7
.equ tmp_110, _stack_base + 10
.equ tmp_112, _stack_base + 13
.equ tmp_113, _stack_base + 15
.equ tmp_115, _stack_base + 19
.equ tmp_117, _stack_base + 21
.equ tmp_118, _stack_base + 23
.equ _s610f894f, _stack_base + 27

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

pymcu_time__delay_us_avr:
	MOV	R14, R24
	LDI	R24, 0
	MOV	R9, R24
L_5:
	MOV	R24, R9
	MOV	R18, R14
	CP	R24, R18
	BRSH	L_6
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
	INC	R9
	JMP	L_5
L_6:
	RET
_s4e65a6dd:
	STD	Y+27, R24
	STD	Y+28, R25
	LDI	R24, 0
	MOV	R11, R24
	LDD	R30, Y+27
	LDD	R31, Y+28
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R12, R24
L_164:
	MOV	R24, R12
	CPI	R24, 0
	BREQ	L_165
	CALL	__pymcu_outline_0
	INC	R11
	LDD	R30, Y+27
	LDD	R31, Y+28
	MOV	R24, R11
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R12, R24
	JMP	L_164
L_165:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	SBI	0x07, 0
	SBI	0x07, 1
	CBI	0x07, 2
	SBI	0x07, 3
	CBI	0x08, 0
	CBI	0x08, 1
	LDI	R24, 1
	MOV	R4, R24
	SBI	0x08, 3

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_1

	LDI	R24, 165
	MOV	R10, R24

	CBI	0x08, 3

	MOV	R8, R24
	LDI	R24, 0
	MOV	R3, R24
	MOV	R7, R24
L_310:
	MOV	R24, R7
	CPI	R24, 8
	BRSH	L_311
	MOV	R24, R8
	ANDI	R24, 128
	TST	R24
	BREQ	L_313
	SBI	0x08, 1
	JMP	L_312
L_313:
	CBI	0x08, 1
L_312:
	MOV	R24, R4
	CPI	R24, 1
	BRLO	L_316
	CALL	pymcu_time__delay_us_avr
L_316:
	SBI	0x08, 0
	MOV	R24, R3
	LSL	R24
	MOV	R3, R24
	SBIS	0x06, 2
	JMP	L_BIT_FALSE_5
	LDI	R24, 1
	JMP	L_BIT_DONE_6
L_BIT_FALSE_5:
	LDI	R24, 0
L_BIT_DONE_6:
	TST	R24
	BREQ	L_319
	MOV	R24, R3
	ORI	R24, 1
	MOV	R3, R24
L_319:
	MOV	R24, R4
	CPI	R24, 1
	BRLO	L_323
	CALL	pymcu_time__delay_us_avr
L_323:
	CBI	0x08, 0
	MOV	R24, R8
	LSL	R24
	MOV	R8, R24
	INC	R7
	JMP	L_310
L_311:
	SBI	0x08, 3

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd

	MOV	R24, R10
	LSR	R24
	LSR	R24
	LSR	R24
	LSR	R24
	ANDI	R24, 15
	MOV	R5, R24
	MOV	R24, R10
	ANDI	R24, 15
	MOV	R6, R24
	MOV	R24, R5
	CPI	R24, 10
	BRSH	L_334
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_333
L_334:
	MOV	R24, R5
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+15, R24
	STD	Y+16, R25
	STD	Y+17, R22
	STD	Y+18, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_333:
	MOV	R24, R6
	CPI	R24, 10
	BRSH	L_344
	CLR	R25
	ADIW	R24, 48
	MOV	R2, R24
	CALL	__pymcu_outline_0
	JMP	L_343
L_344:
	MOV	R24, R6
	CLR	R25
	SBIW	R24, 10
	CLR	R22
	CLR	R23
	SUBI	R24, 191
	SBCI	R25, 255
	SBCI	R22, 255
	SBCI	R23, 255
	STD	Y+23, R24
	STD	Y+24, R25
	STD	Y+25, R22
	STD	Y+26, R23
	MOV	R2, R24
	CALL	__pymcu_outline_0
L_343:

	CALL	__pymcu_outline_1

	LDI	R24, lo8(__flash___cstr_2)
	LDI	R25, hi8(__flash___cstr_2)
	CALL	_s4e65a6dd
	CALL	__pymcu_outline_1

L_363:
	JMP	L_363
__pymcu_outline_0:
	MOV	R13, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R13
	STS	0x00C6, R24
	RET
__pymcu_outline_1:
__pymcu_outline_1.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_1.L0
	LDI	R24, 10
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 83, 83, 80, 73, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 68, 58, 0
.balign 2
	.balign 2
__flash___cstr_2:
	.byte 79, 75, 0
.balign 2
	.balign 2
