; Generated by pymcuc for 
; volatile 'tick' -> GPIOR @ 0x3E (ISR-shared, auto-promoted)
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 0

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	timer1_compa_isr
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

timer1_compa_isr:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDI	R24, 1
	OUT	0x1E, R24
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
_s4e65a6dd:
	STD	Y+0, R24
	STD	Y+1, R25
	LDI	R24, 0
	MOV	R2, R24
	LDD	R30, Y+0
	LDD	R31, Y+1
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R3, R24
L_154:
	MOV	R24, R3
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R3
	STS	0x00C6, R24
	INC	R2
	LDD	R30, Y+0
	LDD	R31, Y+1
	MOV	R24, R2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R3, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 5

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 0
	STS	0x0080, R24
	LDI	R24, 4
	STS	0x0081, R24

	LDI	R24, 244
	STS	0x0089, R24
	LDI	R24, 35
	STS	0x0088, R24
	LDS	R24, 0x0081
	ORI	R24, 8
	STS	0x0081, R24
	LDS	R24, 0x006F
	ORI	R24, 2
	STS	0x006F, R24

	LDS	R24, 0x006F
	ORI	R24, 2
	STS	0x006F, R24
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_240:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_240
	LDI	R24, 10
	STS	0x00C6, R24

L_242:

	IN	R24, 0x1E
	CPI	R24, 1
	BRNE	L_244

	LDI	R24, 0
	OUT	0x1E, R24

	SBI	0x03, 5

L_248:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_248
	LDI	R24, 67
	STS	0x00C6, R24

L_252:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_252
	LDI	R24, 10
	STS	0x00C6, R24
L_244:
	JMP	L_242

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 67, 84, 67, 0
.balign 2
	.balign 2
