; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_86, _stack_base + 4
.equ tmp_87, _stack_base + 4

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt


; --- PyMCU AVR Math Runtime ---
; -----------------------------------------------------------------------------
; PyMCU AVR Math Runtime
; -----------------------------------------------------------------------------
;
; __div8: Unsigned 8-bit Division
;   Input:  R24 (Dividend), R18 (Divisor)
;   Output: R24 (Quotient), R25 (Remainder)
;   Clobbers: R25
;
; __mod8: Unsigned 8-bit Modulo
;   Input:  R24 (Dividend), R18 (Divisor)
;   Output: R24 (Remainder)
;   Clobbers: R25
;
; -----------------------------------------------------------------------------

__div8:
    push r16
    ldi r16, 8      ; 8 iterations: one per dividend bit
    clr r25         ; Remainder = 0
    clc             ; Clear carry

__div8_loop:
    rol r24         ; Shift dividend left, MSB into Carry
    rol r25         ; Shift remainder left, Carry into LSB
    brcs __div8_sub ; Remainder overflowed (>= 256) -> must subtract
    cp r25, r18     ; Compare Remainder with Divisor
    brcs __div8_next; Remainder < Divisor: quotient bit = 0

__div8_sub:
    sub r25, r18    ; Remainder -= Divisor
    sec             ; Quotient bit = 1
    rjmp __div8_dec

__div8_next:
    clc             ; Quotient bit = 0

__div8_dec:
    dec r16
    brne __div8_loop

    rol r24         ; Final ROL shifts last quotient bit into R24

    pop r16
    ret

__mod8:
    rcall __div8
    mov r24, r25    ; Move remainder to result register
    ret

; -----------------------------------------------------------------------------
; __divs8 / __mods8: SIGNED 8-bit floor division and modulo (Python semantics).
;   Input:  R24 (Dividend a), R18 (Divisor b)   -- both signed
;   Output: __divs8 -> R24 = floor(a/b)
;           __mods8 -> R24 = a - b*floor(a/b)   (remainder takes the sign of b)
;   Net clobber: R24, R25 (same as __div8; R16/R17/R19 are push/pop-restored).
;
; Strategy: divide the magnitudes with the unsigned core, give the truncating
; quotient/remainder their signs, then apply the single Python floor correction
; (when the signs differ and the remainder is non-zero: q -= 1; r += b).
; -----------------------------------------------------------------------------
__divmods8:
    push r16
    push r17
    push r19
    mov  r19, r24       ; r19 = original a (sign of dividend)
    mov  r17, r18       ; r17 = original b (sign + floor add)
    sbrc r24, 7
    neg  r24            ; |a|
    sbrc r18, 7
    neg  r18            ; |b|
    rcall __div8        ; R24 = |a|/|b| (uq), R25 = |a|%|b| (ur); R18 preserved
    sbrc r19, 7
    neg  r25            ; truncating remainder takes the sign of a
    mov  r16, r19
    eor  r16, r17       ; r16 bit7 = 1 when signs differ (quotient is negative)
    sbrc r16, 7
    neg  r24            ; truncating quotient sign
    sbrs r16, 7
    rjmp __divmods8_done    ; signs equal -> trunc == floor
    tst  r25
    breq __divmods8_done    ; exact -> no correction
    dec  r24            ; floor: q -= 1
    add  r25, r17       ;        r += b
__divmods8_done:
    pop  r19
    pop  r17
    pop  r16
    ret

__divs8:
    rcall __divmods8
    ret                 ; quotient already in R24

__mods8:
    rcall __divmods8
    mov  r24, r25       ; remainder -> result register
    ret


__bad_interrupt:
	JMP	main

safe_div:
	MOV	R7, R24
	MOV	R2, R22

	MOV	R24, R2
	CPI	R24, 0
	BRNE	L_184

	LDI	R22, 1
	SET
	RET
L_184:

	MOV	R24, R2
	TST	R24
	BRNE	L_185
	LDI	R22, 6
	SET
	RET
L_185:
	MOV	R24, R7
	MOV	R18, R2
	CALL	__div8
	MOV	R16, R24
	CLT
	RET
safe_sub:
	MOV	R5, R24
	MOV	R6, R22

	MOV	R18, R6
	CP	R24, R18
	BRSH	L_186

	LDI	R22, 1
	SET
	RET
L_186:

	MOV	R24, R5
	CLR	R25
	MOV	R18, R6
	CLR	R19
	SUB	R24, R18
	SBC	R25, R19
	MOV	R16, R24
	MOV	R17, R25
	CLT
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, 20
	LDI	R22, 4
	CALL	safe_div
	MOV	R3, R24
	BRTC	L_BR_SKIP_3
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_3:

L_196:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_196
	MOV	R24, R3
	STS	0x00C6, R24

	LDI	R24, 10
	LDI	R22, 3
	CALL	safe_sub
	MOV	R4, R24
	BRTC	L_BR_SKIP_5
	JMP	__pymcu_unhandled_exn
L_BR_SKIP_5:

L_200:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_200
	MOV	R24, R4
	STS	0x00C6, R24
	CLT
	RET
; ── Exception runtime ──────────────────────────────────────────────────────
__exn_str_1:
    .byte 69, 58, 86, 97, 108, 117, 101, 69, 114, 114, 111, 114, 13, 10, 0
.balign 2
__exn_str_6:
    .byte 69, 58, 69, 120, 99, 101, 112, 116, 105, 111, 110, 54, 13, 10, 0
.balign 2
    .balign 2

__pymcu_unhandled_exn:
    lds   R16, 0xC1
    sbrs  R16, 3
    rjmp  __exn_halt
    cpi   R22, 1
    breq  __exn_load_1
    cpi   R22, 6
    breq  __exn_load_6
    rjmp  __exn_halt
__exn_load_1:
    ldi   R30, lo8(__exn_str_1)
    ldi   R31, hi8(__exn_str_1)
    rjmp  __exn_print_loop
__exn_load_6:
    ldi   R30, lo8(__exn_str_6)
    ldi   R31, hi8(__exn_str_6)
__exn_print_loop:
    lpm   R16, Z+
    tst   R16
    breq  __exn_halt
__exn_wait_udre:
    lds   R17, 0xC0
    sbrs  R17, 5
    rjmp  __exn_wait_udre
    sts   0xC6, R16
    rjmp  __exn_print_loop
__exn_halt:
    cli
    rjmp  .-2

