; Generated by pymcuc for 
; volatile 'reset_f' -> GPIOR @ 0x3E (ISR-shared, auto-promoted)
; volatile 'start_f' -> GPIOR @ 0x4A (ISR-shared, auto-promoted)
; volatile 'tick_f' -> GPIOR @ 0x4B (ISR-shared, auto-promoted)
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ tmp_93, _stack_base + 4
.equ _s610f894f, _stack_base + 7

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	int0_isr
.org 0x8
	JMP	int1_isr
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	timer0_ovf_isr
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

timer0_ovf_isr:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDI	R24, 1
	OUT	0x2B, R24
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
int0_isr:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDI	R24, 1
	OUT	0x2A, R24
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
int1_isr:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1


	LDI	R24, 1
	OUT	0x1E, R24
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
_s4e65a6dd:
	STD	Y+7, R24
	STD	Y+8, R25
	LDI	R24, 0
	MOV	R6, R24
	LDD	R30, Y+7
	LDD	R31, Y+8
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
L_154:
	MOV	R24, R8
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R8
	STS	0x00C6, R24
	INC	R6
	LDD	R30, Y+7
	LDD	R31, Y+8
	MOV	R24, R6
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R8, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 5

	LDI	R24, 0
	OUT	0x24, R24
	LDI	R24, 5
	OUT	0x25, R24

	LDS	R24, 0x006E
	ORI	R24, 1
	STS	0x006E, R24
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	CBI	0x0A, 2
	SBI	0x0B, 2

	CBI	0x0A, 3
	SBI	0x0B, 3

	LDS	R24, 0x0069
	ANDI	R24, 254
	STS	0x0069, R24
	LDS	R24, 0x0069
	ORI	R24, 2
	STS	0x0069, R24
	SBI	0x1D, 0
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDS	R24, 0x0069
	ANDI	R24, 251
	STS	0x0069, R24
	LDS	R24, 0x0069
	ORI	R24, 8
	STS	0x0069, R24
	SBI	0x1D, 1
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
	LDI	R24, 10
	CALL	__pymcu_outline_0

	LDI	R24, 0
	MOV	R3, R24

	LDI	R25, 0
	MOV	R4, R24
	MOV	R5, R25

	MOV	R2, R24

L_273:

	IN	R24, 0x2A
	CPI	R24, 1
	BRNE	L_275

	LDI	R24, 0
	OUT	0x2A, R24

	MOV	R24, R2
	CPI	R24, 0
	BRNE	L_277

	LDI	R24, 1
	MOV	R2, R24

	SBI	0x05, 5
	JMP	L_276
L_277:

	LDI	R24, 0
	MOV	R2, R24

	CBI	0x05, 5
L_276:
L_275:

	IN	R24, 0x1E
	CPI	R24, 1
	BRNE	L_278

	LDI	R24, 0
	OUT	0x1E, R24

	MOV	R3, R24

	LDI	R25, 0
	MOV	R4, R24
	MOV	R5, R25

	MOV	R2, R24

	CBI	0x05, 5

	CALL	__pymcu_outline_0

	LDI	R24, 10
	CALL	__pymcu_outline_0
L_278:

	IN	R24, 0x2B
	CPI	R24, 1
	BRNE	L_287

	LDI	R24, 0
	OUT	0x2B, R24

	MOV	R24, R2
	CPI	R24, 1
	BRNE	L_288

	INC	R3
	MOV	R24, R3

	CPI	R24, 61
	BRLO	L_289

	LDI	R24, 0
	MOV	R3, R24

	MOV	R24, R4
	MOV	R25, R5
	ADIW	R24, 1
	MOV	R4, R24
	MOV	R5, R25

	LDI	R18, 255
	LDI	R19, 0
	AND	R24, R18
	AND	R25, R19
	MOV	R7, R24
L_292:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_292
	MOV	R24, R7
	STS	0x00C6, R24

	LDI	R24, 10
	CALL	__pymcu_outline_0
L_289:
L_288:
L_287:
	JMP	L_273
__pymcu_outline_0:
	MOV	R9, R24
__pymcu_outline_0.L0:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	__pymcu_outline_0.L0
	MOV	R24, R9
	STS	0x00C6, R24
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 83, 84, 79, 80, 87, 65, 84, 67, 72, 0
.balign 2
	.balign 2
