; Generated by pymcuc for 
; volatile 'flag' -> GPIOR @ 0x3E (ISR-shared, auto-promoted)
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 0
.equ tmp_5, _stack_base + 4

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	_irq_synth_on_press_btn
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_irq_synth_on_press_btn:
; ISR prologue -- save context
	PUSH	R1
	PUSH	R16
	PUSH	R24
	IN	R16, 0x3F
	PUSH	R16
	CLR	R1
	SBIS	0x09, 2
	JMP	L_BIT_FALSE_0
	LDI	R24, 1
	JMP	L_BIT_DONE_1
L_BIT_FALSE_0:
	LDI	R24, 0
L_BIT_DONE_1:
	MOV	R16, R24
	CPI	R24, 0
	BRNE	L_104
	LDI	R24, 1
	OUT	0x1E, R24
L_104:
; ISR epilogue -- restore context
	POP	R16
	OUT	0x3F, R16
	POP	R24
	POP	R16
	POP	R1
	RETI
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	SBI	0x04, 5

	CBI	0x0A, 2

	LDI	R24, 0
	OUT	0x1E, R24

	LDS	R24, 0x0069
	ANDI	R24, 254
	STS	0x0069, R24
	LDS	R24, 0x0069
	ORI	R24, 2
	STS	0x0069, R24
	SBI	0x1D, 0
	IN	R24, 0x3F
	ORI	R24, 128
	OUT	0x3F, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_118:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_118
	LDI	R24, 10
	STS	0x00C6, R24

L_120:

	IN	R24, 0x1E
	CPI	R24, 1
	BRNE	L_122

	LDI	R24, 0
	OUT	0x1E, R24

	SBI	0x03, 5

	LDI	R24, lo8(__flash___cstr_1)
	LDI	R25, hi8(__flash___cstr_1)
	CALL	_s4e65a6dd
L_130:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_130
	LDI	R24, 10
	STS	0x00C6, R24
L_122:
	JMP	L_120
_s4e65a6dd:
	STD	Y+0, R24
	STD	Y+1, R25
	LDI	R24, 0
	MOV	R2, R24
	LDD	R30, Y+0
	LDD	R31, Y+1
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R3, R24
L_286:
	MOV	R24, R3
	CPI	R24, 0
	BREQ	L_287
L_289:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_289
	MOV	R24, R3
	STS	0x00C6, R24
	INC	R2
	LDD	R30, Y+0
	LDD	R31, Y+1
	MOV	R24, R2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R3, R24
	JMP	L_286
L_287:
	RET

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 80, 73, 78, 32, 73, 82, 81, 32, 77, 80, 0
.balign 2
	.balign 2
__flash___cstr_1:
	.byte 80, 82, 69, 83, 83, 69, 68, 0
.balign 2
	.balign 2
