; Generated by pymcuc for 
.equ RAMSTART, 0x0100
.equ _stack_base, RAMSTART
.equ RAMEND, 0x08FF
.equ _s610f894f, _stack_base + 1

.org 0x0
.global main
	JMP	main
.org 0x4
	JMP	__bad_interrupt
.org 0x8
	JMP	__bad_interrupt
.org 0xc
	JMP	__bad_interrupt
.org 0x10
	JMP	__bad_interrupt
.org 0x14
	JMP	__bad_interrupt
.org 0x18
	JMP	__bad_interrupt
.org 0x1c
	JMP	__bad_interrupt
.org 0x20
	JMP	__bad_interrupt
.org 0x24
	JMP	__bad_interrupt
.org 0x28
	JMP	__bad_interrupt
.org 0x2c
	JMP	__bad_interrupt
.org 0x30
	JMP	__bad_interrupt
.org 0x34
	JMP	__bad_interrupt
.org 0x38
	JMP	__bad_interrupt
.org 0x3c
	JMP	__bad_interrupt
.org 0x40
	JMP	__bad_interrupt
.org 0x44
	JMP	__bad_interrupt
.org 0x48
	JMP	__bad_interrupt
.org 0x4c
	JMP	__bad_interrupt
.org 0x50
	JMP	__bad_interrupt
.org 0x54
	JMP	__bad_interrupt
.org 0x58
	JMP	__bad_interrupt
.org 0x5c
	JMP	__bad_interrupt
.org 0x60
	JMP	__bad_interrupt
.org 0x64
	JMP	__bad_interrupt

__bad_interrupt:
	JMP	main

_s4e65a6dd:
	STD	Y+1, R24
	STD	Y+2, R25
	LDI	R24, 0
	MOV	R2, R24
	LDD	R30, Y+1
	LDD	R31, Y+2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R4, R24
L_154:
	MOV	R24, R4
	CPI	R24, 0
	BREQ	L_155
L_157:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_157
	MOV	R24, R4
	STS	0x00C6, R24
	INC	R2
	LDD	R30, Y+1
	LDD	R31, Y+2
	MOV	R24, R2
	ADD	R30, R24
	ADC	R31, R1
	LPM	R24, Z
	MOV	R4, R24
	JMP	L_154
L_155:
	RET
main:
	CLR	R1
	LDI	R16, hi8(RAMEND)
	OUT	0x3E, R16
	LDI	R16, lo8(RAMEND)
	OUT	0x3D, R16
	LDI	R28, lo8(_stack_base)
	LDI	R29, hi8(_stack_base)

	SBI	0x04, 5

	SBI	0x0A, 1
	CBI	0x0A, 0
	LDI	R24, 103
	STS	0x00C4, R24
	LDI	R24, 0
	STS	0x00C5, R24
	LDI	R24, 6
	STS	0x00C2, R24
	LDI	R24, 24
	STS	0x00C1, R24

	LDI	R24, lo8(__flash___cstr_0)
	LDI	R25, hi8(__flash___cstr_0)
	CALL	_s4e65a6dd
L_250:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_250
	LDI	R24, 10
	STS	0x00C6, R24

L_252:

L_257:
	LDS	R24, 0x00C0
	ANDI	R24, 128
	BREQ	L_257
	LDS	R24, 0x00C6
	MOV	R3, R24

	SBI	0x05, 5

L_264:
	LDS	R24, 0x00C0
	ANDI	R24, 32
	BREQ	L_264
	MOV	R24, R3
	STS	0x00C6, R24

	CBI	0x05, 5
	JMP	L_252

; --- Flash Array Pool (LPM lookup tables, const[uint8[N]]) ---
__flash___cstr_0:
	.byte 82, 69, 65, 68, 89, 0
.balign 2
	.balign 2
